#lang info
(define collection "rkt-pythonize")
(define deps '("base" "uuid"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/manual.rkt" ())))
(define pkg-desc "An LE-to-Python compiler behind one macro")
(define installers (list "installer.rkt"))
(define version "4.0.1")
(define pkg-authors '(zhanghao))
(define license '(Apache-2.0 OR MIT))
