#lang racket/base

;; The conversion is a parameter of the compiler, and a module sets it where it
;; sets the other ones: at the phase the compiler runs in, before the forms it
;; means it for.  This module is one that did, so its own forms below are
;; compiled in camelCase.

(require rackunit
         (for-syntax rackunit)
         rkt-pythonize)

(begin-for-syntax
  (python-name-style 'camel)
  ;; the prelude's names carry a prefix the compiler makes up; pin it so the
  ;; Python below reads the same every time
  (prelude-prefix "")
  ;; the conversion a pass makes and the conversion this module makes are the
  ;; one function, reading the one parameter
  (check-equal? (python-name 'object-ref) "objectRef"))

(module+ test
  ;; a name of the program, the name of a piece, and a keyword argument all
  ;; take their Python names from the one conversion, so they agree
  (check-equal? (#%python-code
                  (define (my-name x) (object-ref x 0))
                  (define (tag #:the-label the-label) the-label)
                  (print (my-name (list 1)) (tag #:the-label 2)))
                (string-append "# generated by rkt-pythonize\n"
                               "\n"
                               "builtin_list = list\n"
                               "\n"
                               "def list(*items):\n"
                               "    return builtin_list(items)\n"
                               "\n"
                               "def objectRef(obj, key):\n"
                               "    return obj[key]\n"
                               "\n"
                               "def myName(x):\n"
                               "    return objectRef(x, 0)\n"
                               "\n"
                               "def tag(*, theLabel):\n"
                               "    return theLabel\n"
                               "\n"
                               "print(myName(list(1)), tag(theLabel=2))\n")))
