#lang racket/base

;; #%python-code takes LE and is the Python it renders; these tests render a
;; program, look at the Python, and run it with python3.

(require rackunit
         racket/port
         racket/string
         racket/system
         rkt-pythonize
         "macros.rkt")

;; python3 first, then python, and PYTHON_EXE overrides both
(define (find-python)
  (define candidates
    (if (getenv "PYTHON_EXE")
        (list (getenv "PYTHON_EXE") "python3" "python")
        (list "python3" "python")))
  (or (for/or ([candidate (in-list candidates)])
        (and candidate (find-executable-path candidate)))
      (error 'test "no Python found: set PYTHON_EXE, or put python3 or python on PATH")))

(define (run-python code)
  (define out (open-output-string))
  (define err (open-output-string))
  (define status
    (parameterize ([current-output-port out] [current-error-port err])
      (system* (find-python) "-c" code)))
  (values status (get-output-string out) (get-output-string err)))

;; the macro renders while the module compiles, so a program that has to be
;; refused is expanded at run time here, where the failure can be caught
(define (python-of-data forms)
  (parameterize ([current-namespace (make-base-namespace)])
    (eval '(require rkt-pythonize))
    (eval `(#%python-code ,@forms))))

(define (refuses? forms)
  (with-handlers ([exn:fail? (lambda (e) #t)])
    (python-of-data forms)
    #f))

;; what a program that has to be refused is refused with
(define (refusal-message forms)
  (with-handlers ([exn:fail? (lambda (e) (exn-message e))])
    (python-of-data forms)
    #f))

;; a program whose macros are defined in the namespace it is expanded in: a
;; macro is visible where its name is bound, and an eval'd defmacro binds it
;; there
(define (python-of-data-with defs forms)
  (parameterize ([current-namespace (make-base-namespace)])
    (eval '(require rkt-pythonize))
    (for ([d (in-list defs)]) (eval d))
    (eval `(#%python-code ,@forms))))

(define (refusal-message-with defs forms)
  (with-handlers ([exn:fail? (lambda (e) (exn-message e))])
    (python-of-data-with defs forms)
    #f))

(define (python-output code)
  (define-values (status out err) (run-python code))
  (unless (eq? status #t) (error 'test "python failed: ~a" err))
  out)

(module+ test
  (test-case "a program renders to Python, and the rendering is a string"
    (define code
      (#%python-code
        (define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
        (print (fact 5))))
    (check-true (string? code))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def fact(n):\n"
                                 "    return (1 if (n == 0) is not False else (n * fact((n - 1))))\n"
                                 "\n"
                                 "print(fact(5))\n"))
    (check-equal? (python-output code) "120\n"))

  (test-case "statements: define, set!, begin and a statement if"
    (check-equal? (python-output
                   (#%python-code
                     (define x 0)
                     (set! x (+ x 1))
                     (begin (set! x (* x 10)) (print x))
                     (if (> x 1) (set! x 0) (set! x 99))
                     (print x)))
                  "10\n0\n"))

  (test-case "a procedure takes several bodies and a rest parameter"
    (check-equal? (python-output
                   (#%python-code
                     (define (biggest first . rest)
                       (print first)
                       (apply max (list first (apply max rest))))
                     (print (biggest 1 2 3))
                     (define (tag a . rest) (list a rest))
                     (print (tag 1 2))))
                  "1\n3\n[1, [2]]\n"))

  (test-case "only #f is false"
    (check-equal? (python-output
                   (#%python-code
                     (print (if 0 "0 is true" "0 is false"))
                     (print (if (quote ()) "() is true" "() is false"))
                     (print (if #f "no" "yes"))))
                  "0 is true\n() is true\nyes\n"))

  (test-case "raise and with-handler"
    (check-equal? (python-output
                   (#%python-code
                     (define (recover e) (+ e 1))
                     (print (with-handler recover (raise 41)))
                     (print (if #f (with-handler recover (raise 1)) 7))))
                  "42\n7\n")
    (define-values (status out err)
      (run-python (#%python-code (raise "boom"))))
    (check-not-eq? status #t)
    (check-regexp-match #rx"_Raised" err))

  (test-case "trampoline calls the function the last body returns, and stays flat"
    (check-equal? (python-output
                   (#%python-code
                     (define (count n acc)
                       (if (= n 0) acc (lambda () (count (- n 1) (+ acc 1)))))
                     (print (trampoline (count 100000 0)))))
                  "100000\n"))

  (test-case "names are munged and carry their runtime piece"
    (define code
      (#%python-code
        (define xs (list 1 2 3))
        (object-set! xs 0 10)
        (print (object-ref xs 0))
        (print (object-has-attr? xs "append"))
        (print xs)))
    (check-true (string-contains? code "object_set_b("))
    (check-true (string-contains? code "object_has_attr_p("))
    (check-equal? (python-output code) "10\nTrue\n[10, 2, 3]\n"))

  (test-case "a with-handler body can be statements"
    (define code
      (#%python-code
        (define (recover e) (+ e 100))
        (define x 0)
        (define (boom)
          (set! x 1)
          (with-handler recover (set! x (+ x 1)) (raise 1)))
        (print (boom))
        (print x)))
    (check-true (string-contains? code "global x"))
    (check-equal? (python-output code) "101\n2\n"))

  (test-case "a trampoline body can be statements"
    (check-equal? (python-output
                   (#%python-code
                     (define (count n)
                       (trampoline
                         (print n)
                         (if (= n 0) "done" (count (- n 1)))))
                     (print (count 2))))
                  "2\n1\n0\ndone\n"))

  (test-case "a trampoline body with a statement hoists a def"
    (define code
      (#%python-code
        (define x 0)
        (define (count n)
          (if (= n 0) x (lambda () (count (- n 1)))))
        (print (trampoline (set! x 1) (count 3)))
        (print x)))
    (check-true (string-contains? code "def _lift"))
    (check-equal? (python-output code) "1\n1\n"))

  (test-case "import is an expression, and the module is a value"
    (check-equal? (python-output
                   (#%python-code
                     (define math (import math))
                     (print ((object-get-attr math "sqrt") 16))
                     (print (object-has-attr? (import "math") "floor"))
                     (print (object-has-attr? (import math) "pi"))))
                  "4.0\nTrue\nTrue\n")
    (check-true (refuses? '((import))))
    (check-true (refuses? '((import math os)))))

  (test-case "a lifted lambda takes what it captures"
    (define code
      (#%python-code
        (define (adder n) (lambda (x) (+ x n)))
        (define add3 (adder 3))
        (print (add3 4))
        (print ((adder 10) 5))))
    (check-true (string-contains? code "def _lift"))
    (check-equal? (python-output code) "7\n15\n"))

  (test-case "a lambda body can be statements"
    (check-equal? (python-output
                   (#%python-code
                     (define (add-twice n)
                       ((lambda (x)
                          (define y (+ x 1))
                          (set! y (+ y n))
                          y)
                        10))
                     (print (add-twice 5))))
                  "16\n"))

  (test-case "a lambda takes a rest parameter"
    (check-equal? (python-output
                   (#%python-code
                     (define f (lambda (a . rest) (list a rest)))
                     (print (f 1 2 3))))
                  "[1, [2, 3]]\n"))

  (test-case "a capturing lambda passes its rest parameter on"
    (check-equal? (python-output
                   (#%python-code
                     (define (tagger n) (lambda (a . rest) (list n a rest)))
                     (print ((tagger 1) 2 3 4))))
                  "[1, 2, [3, 4]]\n"))

  (test-case "a local procedure is lifted, and may recurse"
    (check-equal? (python-output
                   (#%python-code
                     (define (sum-to n)
                       (define (loop i acc) (if (= i 0) acc (loop (- i 1) (+ acc i))))
                       (loop n 0))
                     (print (sum-to 4))))
                  "10\n"))

  (test-case "two local procedures may call each other"
    (check-equal? (python-output
                   (#%python-code
                     (define (parity n)
                       (define (ev? i) (if (= i 0) "even" (od? (- i 1))))
                       (define (od? i) (if (= i 0) "odd" (ev? (- i 1))))
                       (ev? n))
                     (print (parity 7))))
                  "odd\n"))

  (test-case "a lifted procedure cannot set! what it captures"
    (check-true (refuses? '((define (counter)
                              (define n 0)
                              (define (bump) (set! n (+ n 1)))
                              (bump)
                              n))))
    (check-true (refuses? '((define (outer a)
                              (define (f) a)
                              (lambda (a) (f)))))))

  (test-case "lambda is a value whose body is one expression"
    (check-equal? (python-output
                   (#%python-code
                     (define add1 (lambda (x) (+ x 1)))
                     (print (add1 2))
                     (print ((lambda (x y) (+ x y)) 3 4))
                     (print (apply (lambda (a b) (* a b)) (list 2 5)))))
                  "3\n7\n10\n")
    (check-true (refuses? '((lambda (x)))))
    (check-true (refuses? '((define (f))))))

  (test-case "the prelude is only what the program asked for"
    (define plain (#%python-code (print "hi")))
    (check-false (string-contains? plain "importlib"))
    (check-false (string-contains? plain "_trampoline"))
    (check-false (string-contains? plain "_with_handler"))
    (check-false (string-contains? plain "_raise"))
    (check-equal? (python-output plain) "hi\n")
    ;; with-handler catches _Raised, so it has to bring raise along
    (define handled
      (#%python-code (print (with-handler (lambda (e) 0) (object-ref (list) 5)))))
    (check-true (string-contains? handled "_Raised"))
    (check-false (string-contains? handled "_trampoline"))
    (check-equal? (python-output handled) "0\n")
    ;; a trampoline program carries its piece and nothing else
    (define looping
      (#%python-code
        (define (count n) (if (= n 0) "done" (lambda () (count (- n 1)))))
        (print (trampoline (count 3)))))
    (check-true (string-contains? looping "_trampoline"))
    (check-false (string-contains? looping "importlib"))
    (check-equal? (python-output looping) "done\n"))

  (test-case "operators are syntax, by arity"
    (check-equal? (python-output
                   (#%python-code
                     (print (+ 1 2 3))
                     (print (+ 1 2))
                     (print (+ 5))
                     (print (- 10 1 2))
                     (print (- 5))
                     (print (modulo 7 2))
                     (print (expt 2 3))
                     (print (& 12 10))
                     (print (\| 12 10))
                     (print (^ 12 10))
                     (print (~ 12))
                     (print (<< 1 4))
                     (print (>> 16 2))
                     (print (not= 1 2))
                     (print (= 1 1))
                     (print (in 2 (list 1 2 3)))
                     (print (not (in 5 (list 1 2 3))))))
                  "6\n3\n5\n7\n-5\n1\n8\n8\n14\n6\n-13\n16\n4\nTrue\nTrue\nTrue\nTrue\n")
    ;; with two or more operands + is infix, with one it is the operand itself
    (define code
      (#%python-code
        (print (+ 1 2))
        (print (+ 5))))
    (check-true (string-contains? code "print((1 + 2))"))
    (check-true (string-contains? code "print(5)"))
    (check-true (refuses? '((print +))))
    (check-true (refuses? '((& 1))))
    (check-true (refuses? '((not 1 2)))))

  (test-case "a name the program never defines is a warning, not an error"
    ;; the compiler logs its warnings, so listen to the logger
    (define (warnings-of forms)
      (define logger (make-logger))
      (define receiver (make-log-receiver logger 'warning))
      (define messages '())
      (parameterize ([current-logger logger]) (python-of-data forms))
      (let loop ()
        (define message (sync/timeout 0.3 receiver))
        (when message
          (set! messages (append messages (list (vector-ref message 1))))
          (loop)))
      (string-join messages " "))
    (check-true (string-contains? (warnings-of '((print nowhere))) "nowhere"))
    (check-true (string-contains? (warnings-of '((set! nowhere 1))) "nowhere"))
    (check-false (string-contains? (warnings-of '((define x 1) (print (+ x 1))))
                                   "warning"))
    (check-false (string-contains? (warnings-of '((print (len "abc")))) "warning"))
    (check-false (string-contains? (warnings-of '((print (object-ref (list 1 2) 0))))
                                   "warning"))
    (check-false (string-contains? (warnings-of '((define (f a . rest) (print rest)) (f 1 2)))
                                   "warning")))

  (test-case "quoted data has no symbols"
    (check-equal? (python-output
                   (#%python-code (print (quote (1 "a" #t)))))
                  "[1, 'a', True]\n")
    (check-true (refuses? '((print (quote a))))))

  (test-case "a statement where an expression belongs is refused"
    (check-true (refuses? '((print (define x 1)))))
    (check-true (refuses? '((print (if #t (set! x 1) 2)))))
    (check-true (refuses? '((print (apply + (list 1 2))))))
    (check-true (refuses? '((print (begin (set! x 1) 2)))))
    (check-true (refuses? '((define (f) (set! x 1))))))

  (test-case "cond is the first clause whose test is true, and a clause body is a begin"
    (define code
      (#%python-code
        (define n 3)
        (print (cond [(> n 0) (print "positive") "positive"]
                     [(< n 0) "negative"]
                     [else (print "zero") "zero"]))))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def _begin(*values):\n"
                                 "    return values[-1]\n"
                                 "\n"
                                 "n = 3\n"
                                 "\n"
                                 "print((_begin(print(\"positive\"), \"positive\") if (n > 0) is not False else (\"negative\" if (n < 0) is not False else _begin(print(\"zero\"), \"zero\"))))\n"))
    (check-equal? (python-output code) "positive\npositive\n"))

  (test-case "a cond in statement position holds several statements in a clause body"
    (define code
      (#%python-code
        (define x 0)
        (cond [(= x 0) (define y 1) (set! x (+ y 1)) (print x)]
              [else (print "no")])
        (print x)))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "x = 0\n"
                                 "\n"
                                 "if (x == 0) is not False:\n"
                                 "    y = 1\n"
                                 "    x = (y + 1)\n"
                                 "    print(x)\n"
                                 "else:\n"
                                 "    print(\"no\")\n"
                                 "\n"
                                 "\n"
                                 "print(x)\n"))
    (check-equal? (python-output code) "2\n2\n"))

  (test-case "a cond nests, and one inside a lambda still lifts"
    (define code
      (#%python-code
        (define (size n)
          (cond [(> n 10) (cond [(> n 100) "huge"] [else "big"])]
                [else "small"]))
        (define (adder n)
          (lambda (x) (cond [(> x 0) (+ x n)] [else n])))
        (define add3 (adder 3))
        (print (size 200))
        (print (size 20))
        (print (size 5))
        (print (add3 4))
        (print (add3 -5))))
    (check-true (string-contains? code "def _lift"))
    (check-equal? (python-output code) "huge\nbig\nsmall\n7\n3\n"))

  (test-case "a cond with no else raises when no test is true"
    (define code
      (#%python-code
        (define n 0)
        (print (cond [(> n 0) "positive"]))))
    (check-true (string-contains? code "_raise(\"cond: no clause matched\")"))
    (check-equal? (python-output
                   (#%python-code
                     (define n 1)
                     (print (cond [(> n 0) "positive"]))))
                  "positive\n")
    (define-values (status out err) (run-python code))
    (check-not-eq? status #t)
    (check-regexp-match #rx"_Raised" err))

  (test-case "a cond that is not well formed is refused, and says why"
    (check-true (refuses? '((cond))))
    (check-regexp-match #rx"a cond needs at least one clause"
                        (refusal-message '((cond))))
    (check-regexp-match #rx"else is only legal as the last cond clause"
                        (refusal-message '((cond [else 1] [#t 2]))))
    (check-regexp-match #rx"else is only legal as the last cond clause"
                        (refusal-message '((cond [#t 1] [else 2] [else 3]))))
    (check-regexp-match #rx"an else clause needs a body"
                        (refusal-message '((cond [#t 1] [else]))))
    (check-regexp-match #rx"a cond clause needs a body"
                        (refusal-message '((cond [#t]))))
    (check-regexp-match #rx"a cond clause with => is not supported"
                        (refusal-message '((cond [#t => print] [else 2]))))
    (check-regexp-match #rx"a cond clause is a \\[test body \\.\\.\\.\\] pair"
                        (refusal-message '((cond x))))
    (check-regexp-match #rx"else is a cond keyword"
                        (refusal-message '((cond [#t else] [else 2])))))

  ;; the macros the tests below use: written outside #%python-code, in this
  ;; module, and visible inside it from the defmacro on.  twice and a.twice come
  ;; from tests/macros.rkt, which this module requires -- that is what a syntax
  ;; binding in another module means, and a spaced macro is bound under its
  ;; dotted name, so a.twice is what a require brings in.
  (defmacro (twice-here form) `(begin ,form ,form))
  (defmacro (twice-print form) `(twice-here (print ,form)))
  (defmacro (all . forms) `(list ,@forms))
  (defmacro (sign-of n) `(cond [(> ,n 0) "positive"] [(< ,n 0) "negative"] [else "zero"]))
  (defmacro (bind-fresh value body)
    (define name (gensym 'tmp))
    `(begin (define ,name ,value) ,body))
  ;; one name, three macros: the default space and two of its own
  (defmacro (say form) `(print "plain:" ,form))
  (defmacro #:space left (say form) `(print "left:" ,form))
  (defmacro #:space right (say form) `(print "right:" ,form))
  (defmacro #:space left (all . forms) `(list ,@forms))

  (test-case "a macro is written outside #%python-code and used inside it"
    (define code
      (#%python-code
        (twice-here (print "hi"))
        (print (twice-here 21))))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def _begin(*values):\n"
                                 "    return values[-1]\n"
                                 "\n"
                                 "print(\"hi\")\n"
                                 "print(\"hi\")\n"
                                 "\n"
                                 "print(_begin(21, 21))\n"))
    (check-equal? (python-output code) "hi\nhi\n21\n"))

  (test-case "a macro from another module is used where that module is required"
    (check-equal? (python-output
                   (#%python-code
                     (twice (print "there"))))
                  "there\nthere\n"))

  (test-case "one name can hold a macro in each space, and a plain one too"
    ;; the #:space marker is what tells the three apart, and it reaches the pass
    ;; as data: the body of #%python-code is not Racket-expanded
    (check-equal? (python-output
                   (#%python-code
                     (say "plain")
                     (#:space left (say "l"))
                     (#:space right (say "r"))))
                  "plain: plain\nleft: l\nright: r\n")
    ;; a spaced macro is bound under its dotted name, so that name works too
    (check-equal? (python-output
                   (#%python-code
                     (left.say "dotted")))
                  "left: dotted\n"))

  (test-case "a body's space is its default, and an inner #:space overrides it"
    (check-equal? (python-output
                   (#%python-code #:space left
                     (say "one")
                     (#:space right (say "two"))
                     (say "three")
                     (#:space #f (say "plain"))))
                  "left: one\nright: two\nleft: three\nplain: plain\n"))

  (test-case "a #:space form nests: an argument may carry a space of its own"
    ;; the outer macro gets the marked form as data and splices it, and only
    ;; then is it expanded, in the space it names
    (check-equal? (python-output
                   (#%python-code #:space left
                     (say (#:space right (say "inner")))))
                  "right: inner\nleft: None\n"))

  (test-case "a spaced macro from another module is used by its space"
    ;; tests/macros.rkt provides a.twice
    (check-equal? (python-output
                   (#%python-code
                     (#:space a (twice (print "there")))))
                  "a:\nthere\nthere\n"))

  (test-case "the space is not one of the macro's arguments"
    ;; a plain name in a spaced body is looked up in that space, and the marked
    ;; form hands the macro its own arguments and nothing else
    (check-equal? (python-output
                   (#%python-code #:space left
                     (print (all 1 2 3))))
                  "[1, 2, 3]\n")
    (check-equal? (python-output
                   (#%python-code
                     (print (#:space left (all 4 5)))))
                  "[4, 5]\n"))

  (test-case "a spaced use that names no macro is refused, and says which space"
    (check-regexp-match #rx"no macro named say in space nowher"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space nowher (say 1)))))
    ;; the space is in the other errors too
    (check-regexp-match #rx"the macro left.one takes 1 argument, and is given 2 arguments"
                        (refusal-message-with '((defmacro #:space left (one x) x))
                                              '((#:space left (one 1 2)))))
    (check-regexp-match #rx"the macro left.boom failed:"
                        (refusal-message-with '((defmacro #:space left (boom x) (car x)))
                                              '((#:space left (boom 1)))))
    ;; and no #:space form may be left for the passes after this one
    (check-regexp-match #rx"a #:space form names a space and a macro"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space))))
    (check-regexp-match #rx"a #:space form names one macro"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space left (say 1) (say 2)))))
    ;; a marked form is a macro call: a name that is no macro in that space is
    ;; named, and so is a form whose head is no name at all
    (check-regexp-match #rx"no macro named if in space left"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space left (if #t 1 2)))))
    (check-regexp-match #rx"a #:space form names a macro"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space left ((print 1) 2)))))
    (check-regexp-match #rx"a #:space marker has to start a macro call"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((print #:space)))))

  (test-case "a macro's name shadows an LE name of the same name"
    ;; the macro is the syntax inside #%python-code, so the procedure the
    ;; program defines under that name is never the thing that is called
    (check-equal? (python-output
                   (#%python-code
                     (define (say x) (print "procedure:" x))
                     (say "here")))
                  "plain: here\n"))

  (test-case "a plain use of a name that only lives in a space is a Python call"
    ;; the pass cannot tell that apart from a name the program uses, so it does
    ;; not: today's behaviour stays
    (define code
      (python-of-data-with '((defmacro #:space left (say x) `(print ,x)))
                           '((print (say 1)))))
    (check-true (string-contains? code "print(say(1))")))

  (test-case "a macro may expand into another macro"
    (check-equal? (python-output
                   (#%python-code
                     (twice-print "again")))
                  "again\nagain\n"))

  (test-case "a macro with a rest parameter collects the argument forms"
    (check-equal? (python-output
                   (#%python-code
                     (print (all 1 2 3))))
                  "[1, 2, 3]\n")
    (check-equal? (python-output
                   (#%python-code
                     (print (all 7))))
                  "[7]\n"))

  (test-case "a macro may expand into a cond"
    (check-equal? (python-output
                   (#%python-code
                     (print (sign-of 5))
                     (print (sign-of -5))
                     (print (sign-of 0))))
                  "positive\nnegative\nzero\n"))

  (test-case "gensym gives a macro a name of its own"
    (define code
      (#%python-code
        (define n 1)
        (bind-fresh 7 (print (+ n 1)))))
    (check-regexp-match #rx"tmp[0-9]+ = 7" code)
    (check-equal? (python-output code) "2\n"))

  (test-case "a macro that misbehaves is a compile error, and says why"
    (check-regexp-match #rx"more than 1000 macro expansions"
                        (refusal-message-with '((defmacro (loop x) `(loop ,x)))
                                              '((loop 1))))
    (check-regexp-match #rx"the macro one takes 1 argument, and is given 2 arguments"
                        (refusal-message-with '((defmacro (one x) x))
                                              '((one 1 2))))
    (check-regexp-match #rx"the macro at-least takes at least 1 argument, and is given 0"
                        (refusal-message-with '((defmacro (at-least a . rest) a))
                                              '((at-least))))
    (check-regexp-match #rx"the macro boom failed:"
                        (refusal-message-with '((defmacro (boom x) (car x)))
                                              '((boom 1))))
    (check-regexp-match #rx"returned a syntax object"
                        (refusal-message-with '((defmacro (syn x) #'(print x)))
                                              '((syn 1))))
    (check-regexp-match #rx"expanded into #<void>, which is not a form"
                        (refusal-message-with '((defmacro (nothing x) (void)))
                                              '((nothing 1)))))

  (test-case "a name that is not a macro is still a Python global"
    ;; a phase-1 procedure, and an ordinary Racket macro, are not defmacros
    (define code
      (python-of-data-with '((begin-for-syntax (define (helper x) x)))
                           '((print (helper 1)))))
    (check-true (string-contains? code "print(helper(1))"))
    (check-equal? (refusal-message-with '((defmacro (twice x) `(begin ,x ,x)))
                                        '((let ([x 1]) x)))
                  (refusal-message '((let ([x 1]) x)))))

  (test-case "a Racket form is not LE, and says so"
    (check-true (refuses? '((let ([x 1]) x))))
    (check-true (refuses? '((when #t 1))))
    (check-true (refuses? '((define-syntax-rule (m x) x))))))
