#lang racket/base

;; #%python-code takes LE and is the Python it renders; these tests render a
;; program, look at the Python, and run it with python3.

(require rackunit
         racket/file
         racket/port
         racket/string
         racket/system
         rkt-pythonize
         "macros.rkt")

;; python3 first, then python, and PYTHON_EXE overrides both
(define (find-python)
  (define candidates
    (if (getenv "PYTHON_EXE")
        (list (getenv "PYTHON_EXE") "python3" "python")
        (list "python3" "python")))
  (or (for/or ([candidate (in-list candidates)])
        (and candidate (find-executable-path candidate)))
      (error 'test "no Python found: set PYTHON_EXE, or put python3 or python on PATH")))

;; a program goes in a file: the command line has its own limit, and a chain a
;; thousand steps long reaches it
(define (program-file)
  (define dir (build-path (current-directory) ".tmp"))
  (make-directory* dir)
  (make-temporary-file "rkt-pythonize-~a.py" #f dir))

(define (run-python code)
  (define out (open-output-string))
  (define err (open-output-string))
  (define file (program-file))
  (call-with-output-file file #:exists 'truncate (lambda (o) (display code o)))
  (define status
    (parameterize ([current-output-port out] [current-error-port err])
      (system* (find-python) (path->string file))))
  (delete-file file)
  (values status (get-output-string out) (get-output-string err)))

;; the macro renders while the module compiles, so a program that has to be
;; refused is expanded at run time here, where the failure can be caught
;; the prelude's names carry a prefix the compiler makes up; a test pins it, so
;; the Python it looks at reads the same every time
(define (pin-prelude!)
  (eval '(begin-for-syntax (prelude-prefix ""))))

(define (python-of-data forms)
  (parameterize ([current-namespace (make-base-namespace)])
    (eval '(require rkt-pythonize))
    (pin-prelude!)
    (eval `(#%python-code ,@forms))))

(define (refuses? forms)
  (with-handlers ([exn:fail? (lambda (e) #t)])
    (python-of-data forms)
    #f))

;; what a program that has to be refused is refused with
(define (refusal-message forms)
  (with-handlers ([exn:fail? (lambda (e) (exn-message e))])
    (python-of-data forms)
    #f))

;; a program whose macros are defined in the namespace it is expanded in: a
;; macro is visible where its name is bound, and an eval'd defmacro binds it
;; there
(define (python-of-data-with defs forms)
  (parameterize ([current-namespace (make-base-namespace)])
    (eval '(require rkt-pythonize))
    (pin-prelude!)
    (for ([d (in-list defs)]) (eval d))
    (eval `(#%python-code ,@forms))))

(define (refusal-message-with defs forms)
  (with-handlers ([exn:fail? (lambda (e) (exn-message e))])
    (python-of-data-with defs forms)
    #f))

;; a program compiled in another style: the style is a parameter of the
;; compiler, so it is set at the phase the compiler runs in, before the form
(define (python-of-data-in-style style forms)
  (parameterize ([current-namespace (make-base-namespace)])
    (eval '(require rkt-pythonize))
    (pin-prelude!)
    (eval `(begin-for-syntax (python-name-style ',style)))
    (eval `(#%python-code ,@forms))))

;; and a test that is about the prefix pins it to something it can read
(define (python-of-data-with-prefix prefix forms)
  (parameterize ([current-namespace (make-base-namespace)])
    (eval '(require rkt-pythonize))
    (eval `(begin-for-syntax (prelude-prefix ,prefix)))
    (eval `(#%python-code ,@forms))))

(define (refusal-message-in-style style forms)
  (with-handlers ([exn:fail? (lambda (e) (exn-message e))])
    (python-of-data-in-style style forms)
    #f))

;; the warnings the compiler logs for a program, which is how a name the
;; program never binds is seen
(define (warnings-of forms [style 'snake])
  (define logger (make-logger))
  (define receiver (make-log-receiver logger 'warning))
  (define messages '())
  (parameterize ([current-logger logger]) (python-of-data-in-style style forms))
  (let loop ()
    (define message (sync/timeout 0.3 receiver))
    (when message
      (set! messages (append messages (list (vector-ref message 1))))
      (loop)))
  (string-join messages " "))

(define (python-output code)
  (define-values (status out err) (run-python code))
  (unless (eq? status #t) (error 'test "python failed: ~a" err))
  out)

(module+ test
  ;; the prelude's prefix is pinned for this module too, so the forms below read
  ;; the Python they expect
  (begin-for-syntax (prelude-prefix ""))

  (test-case "a program renders to Python, and the rendering is a string"
    (define code
      (#%python-code
        (define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
        (print (fact 5))))
    (check-true (string? code))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def fact(n):\n"
                                 "    return (1 if (n == 0) is not False else (n * fact((n - 1))))\n"
                                 "\n"
                                 "print(fact(5))\n"))
    (check-equal? (python-output code) "120\n"))

  (test-case "statements: define, set!, begin and a statement if"
    (check-equal? (python-output
                   (#%python-code
                     (define x 0)
                     (set! x (+ x 1))
                     (begin (set! x (* x 10)) (print x))
                     (if (> x 1) (set! x 0) (set! x 99))
                     (print x)))
                  "10\n0\n"))

  (test-case "a procedure takes several bodies and a rest parameter"
    (check-equal? (python-output
                   (#%python-code
                     (define (biggest first . rest)
                       (print first)
                       (apply max (list first (apply max rest))))
                     (print (biggest 1 2 3))
                     (define (tag a . rest) (list a rest))
                     (print (tag 1 2))))
                  "1\n3\n[1, [2]]\n"))

  (test-case "only #f is false"
    (check-equal? (python-output
                   (#%python-code
                     (print (if 0 "0 is true" "0 is false"))
                     (print (if (quote ()) "() is true" "() is false"))
                     (print (if #f "no" "yes"))))
                  "0 is true\n() is true\nyes\n"))

  (test-case "raise and with-handler"
    (check-equal? (python-output
                   (#%python-code
                     (define (recover e) (+ e 1))
                     (print (with-handler recover (raise 41)))
                     (print (if #f (with-handler recover (raise 1)) 7))))
                  "42\n7\n")
    (define-values (status out err)
      (run-python (#%python-code (raise "boom"))))
    (check-not-eq? status #t)
    (check-regexp-match #rx"Raised" err))

  (test-case "trampoline calls the function the last body returns, and stays flat"
    (check-equal? (python-output
                   (#%python-code
                     (define (count n acc)
                       (if (= n 0) acc (lambda () (count (- n 1) (+ acc 1)))))
                     (print (trampoline (count 100000 0)))))
                  "100000\n"))

  (test-case "a name is converted and carries its runtime piece"
    (define code
      (#%python-code
        (define xs (list 1 2 3))
        (object-set! xs 0 10)
        (print (object-ref xs 0))
        (print (object-has-attr? xs "append"))
        (print xs)))
    (check-true (string-contains? code "object_set_b("))
    (check-true (string-contains? code "object_has_attr_p("))
    (check-equal? (python-output code) "10\nTrue\n[10, 2, 3]\n"))

  (test-case "a with-handler body can be statements"
    (define code
      (#%python-code
        (define (recover e) (+ e 100))
        (define x 0)
        (define (boom)
          (set! x 1)
          (with-handler recover (set! x (+ x 1)) (raise 1)))
        (print (boom))
        (print x)))
    (check-true (string-contains? code "global x"))
    (check-equal? (python-output code) "101\n2\n"))

  (test-case "a trampoline body can be statements"
    (check-equal? (python-output
                   (#%python-code
                     (define (count n)
                       (trampoline
                         (print n)
                         (if (= n 0) "done" (count (- n 1)))))
                     (print (count 2))))
                  "2\n1\n0\ndone\n"))

  (test-case "a trampoline body with a statement hoists a def"
    (define code
      (#%python-code
        (define x 0)
        (define (count n)
          (if (= n 0) x (lambda () (count (- n 1)))))
        (print (trampoline (set! x 1) (count 3)))
        (print x)))
    (check-true (string-contains? code "def _lift"))
    (check-equal? (python-output code) "1\n1\n"))

  (test-case "import is an expression, and the module is a value"
    (check-equal? (python-output
                   (#%python-code
                     (define math (import math))
                     (print ((object-get-attr math "sqrt") 16))
                     (print (object-has-attr? (import "math") "floor"))
                     (print (object-has-attr? (import math) "pi"))))
                  "4.0\nTrue\nTrue\n")
    (check-true (refuses? '((import))))
    (check-true (refuses? '((import math os)))))

  (test-case "a lifted lambda takes what it captures"
    (define code
      (#%python-code
        (define (adder n) (lambda (x) (+ x n)))
        (define add3 (adder 3))
        (print (add3 4))
        (print ((adder 10) 5))))
    (check-true (string-contains? code "def _lift"))
    (check-equal? (python-output code) "7\n15\n"))

  (test-case "a lambda body can be statements"
    (check-equal? (python-output
                   (#%python-code
                     (define (add-twice n)
                       ((lambda (x)
                          (define y (+ x 1))
                          (set! y (+ y n))
                          y)
                        10))
                     (print (add-twice 5))))
                  "16\n"))

  (test-case "a lambda takes a rest parameter"
    (check-equal? (python-output
                   (#%python-code
                     (define f (lambda (a . rest) (list a rest)))
                     (print (f 1 2 3))))
                  "[1, [2, 3]]\n"))

  (test-case "a capturing lambda passes its rest parameter on"
    (check-equal? (python-output
                   (#%python-code
                     (define (tagger n) (lambda (a . rest) (list n a rest)))
                     (print ((tagger 1) 2 3 4))))
                  "[1, 2, [3, 4]]\n"))

  (test-case "a procedure takes keyword parameters, and a call writes them"
    (define code
      (#%python-code
        (define (f a #:k k) (+ a k))
        (print (f 1 #:k 2))
        (print (f #:k 2 1))))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def f(a, *, k):\n"
                                 "    return (a + k)\n"
                                 "\n"
                                 "print(f(1, k=2))\n"
                                 "\n"
                                 "print(f(1, k=2))\n"))
    (check-equal? (python-output code) "3\n3\n"))

  (test-case "a keyword name is converted as a name is, on both sides of a call"
    (define code
      (#%python-code
        (define (tag #:even? even?) (if even? "even" "odd"))
        (print (tag #:even? 4))))
    (check-true (string-contains? code "def tag(*, even_p):"))
    (check-true (string-contains? code "tag(even_p=4)"))
    (check-equal? (python-output code) "even\n")
    ;; the call to a Python function converts the keyword it writes the same way
    (define python-call
      (#%python-code
        (define b (bytes (list 1 2 3)))
        (print ((object-get-attr b "hex") "-" #:bytes-per-sep 1))))
    (check-true (string-contains? python-call "bytes_per_sep=1"))
    (check-equal? (python-output python-call) "01-02-03\n"))

  (test-case "a keyword argument reaches a Python function"
    (check-equal? (python-output
                   (#%python-code
                     (print (sorted (list 3 1 2) #:reverse #t))
                     (print (round 2.567 #:ndigits 2))))
                  "[3, 2, 1]\n2.57\n"))

  (test-case "a call may write its keyword arguments where it likes"
    (define code
      (#%python-code
        (define (f a #:k k . rest) (list a k rest))
        (print (f 1 #:k 2 3 4))
        (print (f 1 3 4 #:k 2))))
    (check-true (string-contains? code "def f(a, *rest, k):"))
    (check-true (string-contains? code "rest = [*rest]"))
    (check-true (string-contains? code "print(f(1, 3, 4, k=2))"))
    (check-equal? (python-output code) "[1, 2, [3, 4]]\n[1, 2, [3, 4]]\n"))

  (test-case "a lambda takes keyword parameters, and a lifted one passes them on"
    (define code
      (#%python-code
        (define (adder n) (lambda (x #:k k) (+ x n k)))
        (define add3 (adder 3))
        (print (add3 4 #:k 5))
        (print ((adder 10) 1 #:k 2))))
    (check-true (string-contains? code "def _lift"))
    (check-true (string-contains? code "lambda x, *, k: _lift"))
    (check-equal? (python-output code) "12\n13\n"))

  (test-case "a capturing procedure with a rest parameter spreads keywords too"
    (define code
      (#%python-code
        (define (tagger n)
          (define (inner x #:k k . rest) (list n x k rest))
          inner)
        (print ((tagger 1) 2 #:k 3 4 5))))
    (check-true (string-contains? code "apply(_lift"))
    (check-true (string-contains? code ", k=k)"))
    (check-equal? (python-output code) "[1, 2, 3, [4, 5]]\n"))

  (test-case "apply carries a keyword to the function it calls"
    (check-equal? (python-output
                   (#%python-code (print (apply (lambda (a b) (+ a b)) (list 1) #:b 2))))
                  "3\n"))

  (test-case "a keyword parameter is in scope, and may be set!"
    (define code
      (#%python-code
        (define (counter #:start start) (set! start (+ start 1)) start)
        (print (counter #:start 1))))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def counter(*, start):\n"
                                 "    start = (start + 1)\n"
                                 "    return start\n"
                                 "\n"
                                 "print(counter(start=1))\n"))
    (check-equal? (python-output code) "2\n"))

  (test-case "the Python name of a top-level name is what the conversion says"
    ;; a program that exports its names reads this: every top-level name of the
    ;; program is the Python name of the name the source wrote, and nothing else
    (check-equal? (#%python-code
                    (define (my-func? x) x)
                    (define x-y (my-func? 1)))
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "def my_func_p(x):\n"
                                 "    return x\n"
                                 "\n"
                                 "x_y = my_func_p(1)\n"))
    (define code
      (#%python-code
        (define (set-car! xs v) (object-set! xs 0 v))
        (define (class x) x)
        (define 1st 1)
        (define list-of-names (list 1 2))))
    (check-true (string-contains? code "def set_car_b(xs, v):"))
    (check-true (string-contains? code "def class_(x):"))
    (check-true (string-contains? code "_1st = 1"))
    (check-true (string-contains? code "list_of_names = list(1, 2)")))

  (test-case "two top-level names that are one Python name are refused"
    ;; which way round the two are written does not matter: what is compared is
    ;; the Python name, so the scheme spelling and the Python one meet
    (check-regexp-match #rx"x-y and x_y are both x_y in Python"
                        (refusal-message '((define x-y 1) (define x_y 2))))
    (check-regexp-match #rx"x_y and x-y are both x_y in Python"
                        (refusal-message '((define x_y 1) (define x-y 2))))
    (check-regexp-match #rx"even\\? and even_p are both even_p in Python"
                        (refusal-message '((define (even? x) x) (define even_p 1))))
    (check-regexp-match #rx"even_p and even\\? are both even_p in Python"
                        (refusal-message '((define (even_p x) x) (define (even? x) x))))
    ;; and in camel, where the two spellings of objectRef meet too
    (check-regexp-match #rx"objectRef and object-ref are both objectRef in Python"
                        (refusal-message-in-style 'camel
                                                  '((define objectRef 1)
                                                    (define object-ref 2))))
    ;; the same name twice is the program's own business, as it is in Python
    (check-equal? (python-output
                   (#%python-code (define x 1) (define x 2) (print x)))
                  "2\n"))

  (test-case "the prelude's names carry a prefix, so a program cannot take them"
    ;; the pieces the compiler calls itself are the prefixed ones, whatever the
    ;; program calls its own names
    (define code
      (python-of-data-with-prefix
       "_pz_"
       '((define (_raise x) "the program's raise")
         (define (apply f xs) "the program's apply")
         (define (tagger n)
           (define (inner x . rest) (list n x rest))
           inner)
         (print (with-handler (lambda (e) (+ "caught " e)) (raise "boom")))
         (print ((tagger 1) 2 3)))))
    (check-true (string-contains? code "def _pz_raise_(value):"))
    (check-true (string-contains? code "class _pz_Raised(Exception):"))
    (check-true (string-contains? code "def _pz_apply(function, *arguments, **keywords):"))
    ;; and the program's own names stand beside them
    (check-true (string-contains? code "def _raise(x):"))
    (check-true (string-contains? code "def apply(f, xs):"))
    (check-equal? (python-output code) "caught boom\n[1, 2, [3]]\n")
    ;; a name the program defines is the program's own where it is bound, and
    ;; the prelude's piece is not carried for it at all
    (define shadowed
      (python-of-data-with-prefix
       "_pz_"
       '((define (list . items) items)
         (print (list 1 2)))))
    (check-true (string-contains? shadowed "def list(*items):"))
    (check-false (string-contains? shadowed "_pz_list")))

  (test-case "a name the compiler makes up is made of a UUID"
    (define code
      (#%python-code
        (define (adder n) (lambda (x) (+ x n)))
        (define _lift1 "the program's")
        (define add2 (adder 2))
        (print (add2 3))
        (print _lift1)))
    ;; the program keeps the name it wrote, and the lifted def has one of its own
    (check-true (regexp-match? #px"def _lift_[0-9a-f]{8}\\(n, x\\):" code))
    (check-true (string-contains? code "_lift1 = \"the program's\""))
    (check-equal? (python-output code) "5\nthe program's\n"))

  (test-case "the conversion is a parameter: camel names a program its own way"
    (define code
      (python-of-data-in-style 'camel
                               '((define (even? n) (= (modulo n 2) 0))
                                 (define my-name "camel")
                                 (define (set-car! xs v) (object-set! xs 0 v))
                                 (print (even? 4))
                                 (print my-name))))
    (check-true (string-contains? code "def isEven(n):"))
    (check-true (string-contains? code "myName = \"camel\""))
    (check-true (string-contains? code "def setCarB(xs, v):"))
    ;; the piece the call needs is named the same way as the call
    (check-true (string-contains? code "objectSetB(xs, 0, v)"))
    (check-true (string-contains? code "def objectSetB(obj, key, value):"))
    (check-equal? (python-output code) "True\ncamel\n")
    ;; a keyword argument's name is converted in the style of the moment too
    (define keyworded
      (python-of-data-in-style 'camel
                               '((define (f #:my-key my-key) my-key)
                                 (print (f #:my-key 2)))))
    (check-true (string-contains? keyworded "def f(*, myKey):"))
    (check-true (string-contains? keyworded "f(myKey=2)"))
    (check-equal? (python-output keyworded) "2\n"))

  (test-case "a local procedure is lifted, and may recurse"
    (check-equal? (python-output
                   (#%python-code
                     (define (sum-to n)
                       (define (loop i acc) (if (= i 0) acc (loop (- i 1) (+ acc i))))
                       (loop n 0))
                     (print (sum-to 4))))
                  "10\n"))

  (test-case "two local procedures may call each other"
    (check-equal? (python-output
                   (#%python-code
                     (define (parity n)
                       (define (ev? i) (if (= i 0) "even" (od? (- i 1))))
                       (define (od? i) (if (= i 0) "odd" (ev? (- i 1))))
                       (ev? n))
                     (print (parity 7))))
                  "odd\n"))

  (test-case "a lifted procedure cannot set! what it captures"
    (check-true (refuses? '((define (counter)
                              (define n 0)
                              (define (bump) (set! n (+ n 1)))
                              (bump)
                              n))))
    (check-true (refuses? '((define (outer a)
                              (define (f) a)
                              (lambda (a) (f)))))))

  (test-case "lambda is a value whose body is one expression"
    (check-equal? (python-output
                   (#%python-code
                     (define add1 (lambda (x) (+ x 1)))
                     (print (add1 2))
                     (print ((lambda (x y) (+ x y)) 3 4))
                     (print (apply (lambda (a b) (* a b)) (list 2 5)))))
                  "3\n7\n10\n")
    (check-true (refuses? '((lambda (x)))))
    (check-true (refuses? '((define (f))))))

  (test-case "the prelude is only what the program asked for"
    (define plain (#%python-code (print "hi")))
    (check-false (string-contains? plain "importlib"))
    (check-false (string-contains? plain "trampoline"))
    (check-false (string-contains? plain "with_handler"))
    (check-false (string-contains? plain "raise_"))
    (check-equal? (python-output plain) "hi\n")
    ;; with-handler catches Raised, so it has to bring raise along
    (define handled
      (#%python-code (print (with-handler (lambda (e) 0) (object-ref (list) 5)))))
    (check-true (string-contains? handled "Raised"))
    (check-false (string-contains? handled "trampoline"))
    (check-equal? (python-output handled) "0\n")
    ;; a trampoline program carries its piece and nothing else
    (define looping
      (#%python-code
        (define (count n) (if (= n 0) "done" (lambda () (count (- n 1)))))
        (print (trampoline (count 3)))))
    (check-true (string-contains? looping "trampoline"))
    (check-false (string-contains? looping "importlib"))
    (check-equal? (python-output looping) "done\n"))

  (test-case "operators are syntax, by arity"
    (check-equal? (python-output
                   (#%python-code
                     (print (+ 1 2 3))
                     (print (+ 1 2))
                     (print (+ 5))
                     (print (- 10 1 2))
                     (print (- 5))
                     (print (modulo 7 2))
                     (print (expt 2 3))
                     (print (& 12 10))
                     (print (\| 12 10))
                     (print (^ 12 10))
                     (print (~ 12))
                     (print (<< 1 4))
                     (print (>> 16 2))
                     (print (not= 1 2))
                     (print (= 1 1))
                     (print (in 2 (list 1 2 3)))
                     (print (not (in 5 (list 1 2 3))))))
                  "6\n3\n5\n7\n-5\n1\n8\n8\n14\n6\n-13\n16\n4\nTrue\nTrue\nTrue\nTrue\n")
    ;; with two or more operands + is infix, with one it is the operand itself
    (define code
      (#%python-code
        (print (+ 1 2))
        (print (+ 5))))
    (check-true (string-contains? code "print((1 + 2))"))
    (check-true (string-contains? code "print(5)"))
    (check-true (refuses? '((print +))))
    (check-true (refuses? '((& 1))))
    (check-true (refuses? '((not 1 2)))))

  (test-case "a name the program never defines is a warning, not an error"
    (check-true (string-contains? (warnings-of '((print nowhere))) "nowhere"))
    (check-true (string-contains? (warnings-of '((set! nowhere 1))) "nowhere"))
    (check-false (string-contains? (warnings-of '((define x 1) (print (+ x 1))))
                                   "warning"))
    (check-false (string-contains? (warnings-of '((print (len "abc")))) "warning"))
    (check-false (string-contains? (warnings-of '((print (object-ref (list 1 2) 0))))
                                   "warning"))
    (check-false (string-contains? (warnings-of '((define (f a . rest) (print rest)) (f 1 2)))
                                   "warning"))
    ;; a keyword parameter is a parameter like any other
    (check-false (string-contains? (warnings-of '((define (f #:k k) (print k)) (f #:k 1)))
                                   "warning")))

  (test-case "a name is the Python name the program gives it, either way round"
    ;; the two spellings are one name in the module the program becomes, so
    ;; writing one reaches the other, as a call and as a set!
    (check-equal? (python-output
                   (#%python-code
                     (define (my-func x) (+ x 1))
                     (print (my_func 1))
                     (define x-y 10)
                     (define (bump) (set! x_y 11) x_y)
                     (print (bump))
                     (print x_y)))
                  "2\n11\n11\n")
    ;; and the scope check knows the name is defined, whichever way it is
    ;; written, so it does not warn about it
    (check-false (string-contains? (warnings-of '((define (my-func x) x)
                                                   (print (my_func 1))))
                                   "warning"))
    (check-false (string-contains? (warnings-of '((define x-y 1) (set! x_y 2)))
                                   "no definition"))
    ;; a keyword parameter is bound by its Python name too
    (check-false (string-contains? (warnings-of '((define (f #:my-key my-key) my_key)
                                                   (print (f #:my-key 1))))
                                   "warning"))
    ;; in camel the two spellings are two names, and the free one is said so
    (check-true (string-contains? (warnings-of '((define (my-func x) x)
                                                  (print (my_func 1)))
                                                'camel)
                                  "my_func")))

  (test-case "a set! that assigns no name at all is refused, and says why"
    (check-regexp-match #rx"an assignment takes a name to assign"
                        (refusal-message '((set! 1 2))))
    (check-regexp-match #rx"an assignment takes a name to assign"
                        (refusal-message '((set! (f) 2)))))

  (test-case "a keyword is syntax, not data"
    ;; it belongs in a call or in a parameter list, and nowhere else
    (check-regexp-match #rx"a keyword argument belongs in a call"
                        (refusal-message '((f #:k #:j))))
    (check-regexp-match #rx"a definition of what\\?"
                        (refusal-message '((define #:k 1))))
    ;; a datum is not a keyword, quoted or literal
    (check-regexp-match #rx"a keyword is not data"
                        (refusal-message '((print (quote #:k)))))
    (check-regexp-match #rx"a keyword is not data"
                        (refusal-message '((print (quote (1 #:k))))))
    (check-regexp-match #rx"a keyword is not data"
                        (refusal-message '((print #(1 #:k)))))
    (check-regexp-match #rx"a keyword is not data"
                        (refusal-message '((print #hash(("a" . #:k))))))
    ;; and a macro neither takes one as an argument form nor makes one
    (check-regexp-match #rx"the keyword #:k takes a value"
                        (refusal-message-with '((defmacro (m x) x)) '((m #:k))))
    (check-regexp-match #rx"which is not a form"
                        (refusal-message-with '((defmacro (m) (quote #:k))) '((m)))))

  (test-case "quoted data has no symbols"
    (check-equal? (python-output
                   (#%python-code (print (quote (1 "a" #t)))))
                  "[1, 'a', True]\n")
    (check-true (refuses? '((print (quote a))))))

  (test-case "a statement where an expression belongs is refused"
    (check-true (refuses? '((print (define x 1)))))
    (check-true (refuses? '((print (if #t (set! x 1) 2)))))
    (check-true (refuses? '((print (apply + (list 1 2))))))
    (check-true (refuses? '((print (begin (set! x 1) 2)))))
    (check-true (refuses? '((define (f) (set! x 1))))))

  (test-case "a keyword and the parameter it fills may be spelled either way"
    ;; the keyword and its parameter are one Python name, so #:x-y x_y and
    ;; #:x_y x-y are the one keyword parameter, and either spelling is called
    (check-equal? (python-output
                   (#%python-code
                     (define (f #:x-y x_y) x_y)
                     (print (f #:x-y 1))
                     (print (f #:x_y 2))))
                  "1\n2\n"))

  (test-case "a keyword argument that is not well formed is refused, and says why"
    (check-regexp-match #rx"the keyword #:k takes a value"
                        (refusal-message '((f #:k))))
    (check-regexp-match #rx"the keyword #:k is given twice"
                        (refusal-message '((f #:k 1 #:k 2))))
    ;; two spellings of one Python name are one keyword to the procedure
    (check-regexp-match #rx"the keywords #:x-y and #:x_y are both x_y in Python"
                        (refusal-message '((f #:x-y 1 #:x_y 2))))
    (check-regexp-match #rx"the keywords #:xY and #:x-y are both xY in Python"
                        (refusal-message-in-style 'camel '((f #:xY 1 #:x-y 2))))
    ;; a macro's keywords are Racket's, and Racket tells two of them apart, so
    ;; two spellings of one Python name are two arguments over there
    (check-equal? (python-output
                   (#%python-code
                     (both-keys #:x-y 1 #:x_y 2)))
                  "1 2\n")
    (check-regexp-match #rx"a keyword argument belongs in a call"
                        (refusal-message '((define x #:k))))
    (check-regexp-match #rx"a keyword argument belongs in a call"
                        (refusal-message '((print (if #:k 1 2)))))
    (check-regexp-match #rx"a call starts with a name, not a keyword"
                        (refusal-message '((#:k 1))))
    (check-regexp-match #rx"an operator takes no keyword arguments"
                        (refusal-message '((print (+ 1 #:k 2))))))

  (test-case "a parameter list that is not well formed is refused, and says why"
    (check-regexp-match #rx"the keyword #:k takes a parameter"
                        (refusal-message '((define (f #:k) 1))))
    (check-regexp-match #rx"the keyword #:k is k in Python and its parameter v is v"
                        (refusal-message '((define (f #:k v) v))))
    (check-regexp-match #rx"the parameter a is bound twice"
                        (refusal-message '((define (f a a) a))))
    ;; a parameter list is a list of Python names too, so the two spellings
    ;; meet there, and so do a positional parameter and a keyword's
    (check-regexp-match #rx"the parameters x-y and x_y are both x_y in Python"
                        (refusal-message '((define (f x-y x_y) x-y))))
    (check-regexp-match #rx"the parameters x_y and x-y are both x_y in Python"
                        (refusal-message '((define (f x_y x-y) x_y))))
    (check-regexp-match #rx"the parameters x_y and x-y are both x_y in Python"
                        (refusal-message '((define (f x_y #:x-y x-y) x_y))))
    ;; a keyword and the parameter it fills are one name, either way round
    (check-regexp-match #rx"the keyword #:x-y is x_y in Python and its parameter v is v"
                        (refusal-message '((define (f #:x-y v) v))))
    (check-regexp-match #rx"a parameter is a name"
                        (refusal-message '((define (f 1) 1))))
    (check-regexp-match #rx"a lambda takes a parameter list"
                        (refusal-message '((print (lambda x x))))))

  (test-case "cond is the first clause whose test is true, and a clause body is a begin"
    (define code
      (#%python-code
        (define n 3)
        (print (cond [(> n 0) (print "positive") "positive"]
                     [(< n 0) "negative"]
                     [else (print "zero") "zero"]))))
    ;; a clause body of several forms is a begin where a value belongs, so it is
    ;; lifted into a procedure of its own: statements in a def, and a call to it
    (check-false (string-contains? code "begin("))
    (check-equal? (length (regexp-match* #px"def _lift_[0-9a-f]{8}\\(\\):" code)) 2)
    (check-true (regexp-match?
                 #px"print\\(\\(_lift_[0-9a-f]{8}\\(\\) if \\(n > 0\\) is not False else \\(\"negative\" if \\(n < 0\\) is not False else _lift_[0-9a-f]{8}\\(\\)\\)\\)\\)"
                 code))
    (check-equal? (python-output code) "positive\npositive\n"))

  (test-case "a cond in statement position holds several statements in a clause body"
    (define code
      (#%python-code
        (define x 0)
        (cond [(= x 0) (define y 1) (set! x (+ y 1)) (print x)]
              [else (print "no")])
        (print x)))
    (check-equal? code
                  (string-append "# generated by rkt-pythonize\n"
                                 "\n"
                                 "x = 0\n"
                                 "\n"
                                 "if (x == 0) is not False:\n"
                                 "    y = 1\n"
                                 "    x = (y + 1)\n"
                                 "    print(x)\n"
                                 "else:\n"
                                 "    print(\"no\")\n"
                                 "\n"
                                 "\n"
                                 "print(x)\n"))
    (check-equal? (python-output code) "2\n2\n"))

  (test-case "a cond nests, and one inside a lambda still lifts"
    (define code
      (#%python-code
        (define (size n)
          (cond [(> n 10) (cond [(> n 100) "huge"] [else "big"])]
                [else "small"]))
        (define (adder n)
          (lambda (x) (cond [(> x 0) (+ x n)] [else n])))
        (define add3 (adder 3))
        (print (size 200))
        (print (size 20))
        (print (size 5))
        (print (add3 4))
        (print (add3 -5))))
    (check-true (string-contains? code "def _lift"))
    (check-equal? (python-output code) "huge\nbig\nsmall\n7\n3\n"))

  (test-case "a cond with no else raises when no test is true"
    (define code
      (#%python-code
        (define n 0)
        (print (cond [(> n 0) "positive"]))))
    (check-true (string-contains? code "raise_(\"cond: no clause matched\")"))
    (check-equal? (python-output
                   (#%python-code
                     (define n 1)
                     (print (cond [(> n 0) "positive"]))))
                  "positive\n")
    (define-values (status out err) (run-python code))
    (check-not-eq? status #t)
    (check-regexp-match #rx"Raised" err))

  (test-case "a cond that is not well formed is refused, and says why"
    (check-true (refuses? '((cond))))
    (check-regexp-match #rx"a cond needs at least one clause"
                        (refusal-message '((cond))))
    (check-regexp-match #rx"else is only legal as the last cond clause"
                        (refusal-message '((cond [else 1] [#t 2]))))
    (check-regexp-match #rx"else is only legal as the last cond clause"
                        (refusal-message '((cond [#t 1] [else 2] [else 3]))))
    (check-regexp-match #rx"an else clause needs a body"
                        (refusal-message '((cond [#t 1] [else]))))
    (check-regexp-match #rx"a cond clause needs a body"
                        (refusal-message '((cond [#t]))))
    (check-regexp-match #rx"a cond clause with => is not supported"
                        (refusal-message '((cond [#t => print] [else 2]))))
    (check-regexp-match #rx"a cond clause is a \\[test body \\.\\.\\.\\] pair"
                        (refusal-message '((cond x))))
    (check-regexp-match #rx"else is a cond keyword"
                        (refusal-message '((cond [#t else] [else 2])))))

  ;; the macros the tests below use: written outside #%python-code, in this
  ;; module, and visible inside it from the defmacro on.  twice and a.twice come
  ;; from tests/macros.rkt, which this module requires -- that is what a syntax
  ;; binding in another module means, and a spaced macro is bound under its
  ;; dotted name, so a.twice is what a require brings in.
  (defmacro (twice-here form) `(begin ,form ,form))
  (defmacro (twice-print form) `(twice-here (print ,form)))
  (defmacro (all . forms) `(list ,@forms))
  (defmacro (sign-of n) `(cond [(> ,n 0) "positive"] [(< ,n 0) "negative"] [else "zero"]))
  (defmacro (bind-fresh value body)
    (define name (gensym 'tmp))
    `(begin (define ,name ,value) ,body))
  ;; one name, three macros: the default space and two of its own
  (defmacro (say form) `(print "plain:" ,form))
  (defmacro #:space left (say form) `(print "left:" ,form))
  (defmacro #:space right (say form) `(print "right:" ,form))
  (defmacro #:space left (all . forms) `(list ,@forms))
  ;; a macro's transformer is a Racket procedure, so a keyword argument of a
  ;; macro call is Racket's: it is not converted, and it may carry a default
  ;; a macro's keywords are Racket's: #:x-y and #:x_y are two of them there,
  ;; whatever they would be in Python
  (defmacro (both-keys #:x-y x-y #:x_y x_y) `(print ,x-y ,x_y))
  (defmacro (kw-product x #:by by) `(print (* ,x ,by)))
  (defmacro (kw-default x #:by [by 10]) `(print (* ,x ,by)))
  (defmacro #:space left (kw-product x #:by by) `(print "left" (* ,x ,by)))

  (test-case "a macro is written outside #%python-code and used inside it"
    (define code
      (#%python-code
        (twice-here (print "hi"))
        (print (twice-here 21))))
    ;; the macro's begin stands as a statement where the program wrote one, and
    ;; where the value is wanted it is lifted
    (check-true (string-contains? code "print(\"hi\")\nprint(\"hi\")"))
    (check-true (regexp-match? #px"def _lift_[0-9a-f]{8}\\(\\):\n    21\n    return 21" code))
    (check-true (regexp-match? #px"print\\(_lift_[0-9a-f]{8}\\(\\)\\)" code))
    (check-false (string-contains? code "begin("))
    (check-equal? (python-output code) "hi\nhi\n21\n"))

  (test-case "a macro from another module is used where that module is required"
    (check-equal? (python-output
                   (#%python-code
                     (twice (print "there"))))
                  "there\nthere\n")
    ;; a keyword argument reaches the macro over there too
    (check-equal? (python-output
                   (#%python-code
                     (print (tagged 1 #:tag "there"))))
                  "['there', 1]\n"))

  (test-case "one name can hold a macro in each space, and a plain one too"
    ;; the #:space marker is what tells the three apart, and it reaches the pass
    ;; as data: the body of #%python-code is not Racket-expanded
    (check-equal? (python-output
                   (#%python-code
                     (say "plain")
                     (#:space left (say "l"))
                     (#:space right (say "r"))))
                  "plain: plain\nleft: l\nright: r\n")
    ;; a spaced macro is bound under its dotted name, so that name works too
    (check-equal? (python-output
                   (#%python-code
                     (left.say "dotted")))
                  "left: dotted\n"))

  (test-case "a body's space is its default, and an inner #:space overrides it"
    (check-equal? (python-output
                   (#%python-code #:space left
                     (say "one")
                     (#:space right (say "two"))
                     (say "three")
                     (#:space #f (say "plain"))))
                  "left: one\nright: two\nleft: three\nplain: plain\n"))

  (test-case "a #:space form nests: an argument may carry a space of its own"
    ;; the outer macro gets the marked form as data and splices it, and only
    ;; then is it expanded, in the space it names
    (check-equal? (python-output
                   (#%python-code #:space left
                     (say (#:space right (say "inner")))))
                  "right: inner\nleft: None\n"))

  (test-case "a spaced macro from another module is used by its space"
    ;; tests/macros.rkt provides a.twice
    (check-equal? (python-output
                   (#%python-code
                     (#:space a (twice (print "there")))))
                  "a:\nthere\nthere\n"))

  (test-case "the space is not one of the macro's arguments"
    ;; a plain name in a spaced body is looked up in that space, and the marked
    ;; form hands the macro its own arguments and nothing else
    (check-equal? (python-output
                   (#%python-code #:space left
                     (print (all 1 2 3))))
                  "[1, 2, 3]\n")
    (check-equal? (python-output
                   (#%python-code
                     (print (#:space left (all 4 5)))))
                  "[4, 5]\n"))

  (test-case "a spaced use that names no macro is refused, and says which space"
    (check-regexp-match #rx"no macro named say in space nowher"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space nowher (say 1)))))
    ;; the space is in the other errors too
    (check-regexp-match #rx"the macro left.one takes 1 argument, and is given 2 arguments"
                        (refusal-message-with '((defmacro #:space left (one x) x))
                                              '((#:space left (one 1 2)))))
    (check-regexp-match #rx"the macro left.boom failed:"
                        (refusal-message-with '((defmacro #:space left (boom x) (car x)))
                                              '((#:space left (boom 1)))))
    ;; and no #:space form may be left for the passes after this one
    (check-regexp-match #rx"a #:space form names a space and a macro"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space))))
    (check-regexp-match #rx"a #:space form names one macro"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space left (say 1) (say 2)))))
    ;; a marked form is a macro call: a name that is no macro in that space is
    ;; named, and so is a form whose head is no name at all
    (check-regexp-match #rx"no macro named if in space left"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space left (if #t 1 2)))))
    (check-regexp-match #rx"a #:space form names a macro"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((#:space left ((print 1) 2)))))
    (check-regexp-match #rx"a #:space marker has to start a macro call"
                        (refusal-message-with '((defmacro #:space left (say x) x))
                                              '((print #:space)))))

  (test-case "a macro's name shadows an LE name of the same name"
    ;; the macro is the syntax inside #%python-code, so the procedure the
    ;; program defines under that name is never the thing that is called
    (check-equal? (python-output
                   (#%python-code
                     (define (say x) (print "procedure:" x))
                     (say "here")))
                  "plain: here\n"))

  (test-case "a plain use of a name that only lives in a space is a Python call"
    ;; the pass cannot tell that apart from a name the program uses, so it does
    ;; not: today's behaviour stays
    (define code
      (python-of-data-with '((defmacro #:space left (say x) `(print ,x)))
                           '((print (say 1)))))
    (check-true (string-contains? code "print(say(1))")))

  (test-case "a macro may expand into another macro"
    (check-equal? (python-output
                   (#%python-code
                     (twice-print "again")))
                  "again\nagain\n"))

  (test-case "a macro with a rest parameter collects the argument forms"
    (check-equal? (python-output
                   (#%python-code
                     (print (all 1 2 3))))
                  "[1, 2, 3]\n")
    (check-equal? (python-output
                   (#%python-code
                     (print (all 7))))
                  "[7]\n"))

  (test-case "a macro takes keyword arguments, and they are Racket's"
    (check-equal? (python-output
                   (#%python-code
                     (kw-product 6 #:by 7)))
                  "42\n")
    ;; a macro call writes its keyword arguments where it likes, as Racket does
    (check-equal? (python-output
                   (#%python-code
                     (kw-product #:by 7 6)))
                  "42\n")
    ;; the transformer is a Racket lambda, so a keyword of a macro may default
    (check-equal? (python-output
                   (#%python-code
                     (kw-default 6 #:by 3)))
                  "18\n")
    (check-equal? (python-output
                   (#%python-code
                     (kw-default 6)))
                  "60\n")
    ;; a macro's keyword is the transformer's, not a Python name, so it is not
    ;; munged -- and a spaced macro call carries one too
    (check-equal? (python-output
                   (#%python-code
                     (#:space left (kw-product 2 #:by 3))))
                  "left 6\n"))

  (test-case "a macro call is checked against the keywords the transformer takes"
    (check-regexp-match #rx"the macro m takes 1 argument, and is given 2 arguments"
                        (refusal-message-with '((defmacro (m x #:k k) x))
                                              '((m 1 2 #:k 3))))
    (check-regexp-match #rx"the macro m needs the keyword #:k, and is not given it"
                        (refusal-message-with '((defmacro (m x #:k k) x))
                                              '((m 1))))
    (check-regexp-match #rx"the macro m does not take the keyword #:j"
                        (refusal-message-with '((defmacro (m x #:k k) x))
                                              '((m 1 #:k 2 #:j 3))))
    (check-regexp-match #rx"the keyword #:k takes a value"
                        (refusal-message-with '((defmacro (m x #:k k) x))
                                              '((m 1 #:k)))))

  (test-case "a macro may expand into a cond"
    (check-equal? (python-output
                   (#%python-code
                     (print (sign-of 5))
                     (print (sign-of -5))
                     (print (sign-of 0))))
                  "positive\nnegative\nzero\n"))

  (test-case "gensym gives a macro a name of its own"
    (define code
      (#%python-code
        (define n 1)
        (bind-fresh 7 (print (+ n 1)))))
    (check-regexp-match #rx"tmp[0-9]+ = 7" code)
    (check-equal? (python-output code) "2\n"))

  (test-case "a macro that misbehaves is a compile error, and says why"
    (check-regexp-match #rx"more than 1000 macro expansions"
                        (refusal-message-with '((defmacro (loop x) `(loop ,x)))
                                              '((loop 1))))
    (check-regexp-match #rx"the macro one takes 1 argument, and is given 2 arguments"
                        (refusal-message-with '((defmacro (one x) x))
                                              '((one 1 2))))
    (check-regexp-match #rx"the macro at-least takes at least 1 argument, and is given 0"
                        (refusal-message-with '((defmacro (at-least a . rest) a))
                                              '((at-least))))
    (check-regexp-match #rx"the macro boom failed:"
                        (refusal-message-with '((defmacro (boom x) (car x)))
                                              '((boom 1))))
    (check-regexp-match #rx"returned a syntax object"
                        (refusal-message-with '((defmacro (syn x) #'(print x)))
                                              '((syn 1))))
    (check-regexp-match #rx"expanded into #<void>, which is not a form"
                        (refusal-message-with '((defmacro (nothing x) (void)))
                                              '((nothing 1)))))

  (test-case "a name that is not a macro is still a Python global"
    ;; a phase-1 procedure, and an ordinary Racket macro, are not defmacros
    (define code
      (python-of-data-with '((begin-for-syntax (define (helper x) x)))
                           '((print (helper 1)))))
    (check-true (string-contains? code "print(helper(1))"))
    (check-equal? (refusal-message-with '((defmacro (twice x) `(begin ,x ,x)))
                                        '((let ([x 1]) x)))
                  (refusal-message '((let ([x 1]) x)))))

  (test-case "a Racket form is not LE, and says so"
    (check-true (refuses? '((let ([x 1]) x))))
    (check-true (refuses? '((when #t 1))))
    (check-true (refuses? '((define-syntax-rule (m x) x)))))
  (test-case "a begin where a value belongs is lifted into a procedure of its own"
    (define code
      (#%python-code
        (define (f x) (begin (print "a") (print "b") (+ x 1)))
        (define y (if (begin (print "t") #t) (begin (print "c") 1) 2))
        (define (g) (begin (define z 5)) (* z z))
        (print (f 1)) (print y) (print (g))))
    ;; a body's begin is its statements, and its last form is the value
    (check-true (string-contains?
                 code "def f(x):\n    print(\"a\")\n    print(\"b\")\n    return (x + 1)"))
    ;; a begin in a value's place is a def of its own, called where it stands
    (check-true (regexp-match?
                 #px"def _lift_[0-9a-f]{8}\\(\\):\n    print\\(\"t\"\\)\n    return True" code))
    (check-true (regexp-match?
                 #px"def _lift_[0-9a-f]{8}\\(\\):\n    print\\(\"c\"\\)\n    return 1" code))
    ;; a begin as a statement keeps its definitions where they mean something
    (check-true (string-contains? code "def g():\n    z = 5\n    return (z * z)"))
    (check-false (string-contains? code "begin("))
    (check-equal? (python-output code) "t\nc\na\nb\n2\n1\n25\n"))

  (test-case "a definition in a begin means something in a body and nothing in an expression"
    ;; a begin that stands as a statement has its definitions, and a body's last
    ;; form is an expression, so the begin has to stand before it
    (check-true (string-contains?
                 (python-of-data '((define (g) (begin (define z 5) (print z)) z)))
                 "def g():\n    z = 5\n    print(z)\n    return z"))
    ;; refused, and what it is refused with is what a begin means
    (check-equal? (refusal-message '((print (begin (define z 5) z))))
                  (string-append "check-expression: ?: a begin sequences expressions: "
                                 "a definition belongs in a body, where a name is defined: "
                                 "(define z 5)")))

  (test-case "None, True and False are values to read, not names to bind"
    (check-true (string-contains? (python-of-data '((print None))) "print(None)"))
    (check-true (refuses? '((define None 1))))
    (check-true (refuses? '((define (f True) 1))))
    (check-true (refuses? '((set! False 1)))))
  (test-case "-> threads into the first position and ->> into the last"
    (define code
      (#%python-code
        (define (add1 x) (+ x 1))
        (print (-> 3 (+ 4) (- 1)))
        (print (->> 3 (- 10) (* 2)))
        (print (-> 3 add1))
        (print (->> (list 1 2) (sorted #:reverse #t)))))
    ;; a chain is run by the trampoline, and a begin is nowhere in it
    (check-true (string-contains? code "trampoline("))
    (check-false (string-contains? code "begin("))
    (check-equal? (python-output code) "6\n14\n4\n[2, 1]\n"))

  (test-case "an exception stops the chain, and nothing else does"
    (define code
      (#%python-code
        (define (half x) (if (= x 0) (Exception "zero") (quotient x 2)))
        (define (inc x) (print "inc") (+ x 1))
        (print (-> 8 half inc))
        ;; an Exception, or a subclass of it, is the chain's value, and the steps
        ;; after it do not run
        (print (-> 0 half inc))
        ;; None is a value like any other now
        (print (-> None (list)))
        ;; the value of the last step is handed back even when it is callable
        (print ((-> 5 (object-get-attr "bit_length"))))))
    (check-equal? (python-output code) "inc\n5\nzero\n[None]\n3\n"))

  (test-case "a threading form needs a value and steps that are calls or names"
    (check-true (refuses? '((->))))
    (check-true (refuses? '((-> 1 2))))
    (check-true (refuses? '((-> 1 (quote x)))))
    ;; a value and no steps is the value
    (check-true (string-contains? (python-of-data '((print (-> 7)))) "print(7)\n"))

  (test-case "a chain is flat however many steps it has"
    ;; more steps than Python's own recursion limit: the trampoline is what
    ;; keeps this from nesting a call per step
    (define steps 1200)
    (define code
      (python-of-data-with
       (list `(defmacro (many x)
                ;; one chain of many steps, not a chain of chains
                (let loop ([n ,steps] [seen '()])
                  (if (= n 0)
                      `(-> ,x ,@(reverse seen))
                      (loop (sub1 n) (cons '(add1) seen))))))
       '((define (add1 x) (+ x 1))
         (print (many 0)))))
    (check-equal? (python-output code) (format "~a\n" steps))))
)
