#lang racket/base

;; Macros for tests/dsl.rkt to use from another module: a defmacro is visible
;; where its name is bound, a module that requires this one is one of those
;; places, and a spaced macro is bound under its dotted name, so providing that
;; name is what makes it visible over there.

(require rkt-pythonize)

(provide twice a.twice)

(defmacro (twice form) `(begin ,form ,form))

(defmacro #:space a (twice form) `(begin (print "a:") ,form ,form))

(module+ test
  (require rackunit racket/string)
  ;; and they work in the module that defines them too
  (define code
    (#%python-code
      (twice (print "hi"))))
  (check-equal? code
                (string-append "# generated by rkt-pythonize\n"
                               "\n"
                               "print(\"hi\")\n"
                               "print(\"hi\")\n"))
  (check-equal? (#%python-code
                  (#:space a (twice (print "hi"))))
                (string-append "# generated by rkt-pythonize\n"
                               "\n"
                               "print(\"a:\")\n"
                               "print(\"hi\")\n"
                               "print(\"hi\")\n")))
