#lang racket/base

(require racket/list
         racket/string)

;; LE -> Python.
;;
;; LE is what #%python-code takes: Racket's s-expression syntax, statements and
;; expressions apart, procedures only through define, no macros, no symbols.
;;
;; A statement is what a body, a begin in statement position and the branch of a
;; statement if are made of; an expression is what an if, a call argument and a
;; begin in expression position are made of.  Nothing in an expression position
;; is a statement, so a definition cannot hide inside one and mean something
;; else there, and with-handler and trampoline are expressions like any other:
;; the handler runs where it stands, and a value position guards it.

(provide compile-program)

(define header "# generated by rkt-pythonize\n")

;; names that read better as operators
(define infix
  (for/hash ([p (in-list '((+ . "+") (- . "-") (* . "*") (/ . "/")
                           (= . "==") (< . "<") (> . ">") (<= . "<=") (>= . ">=")
                           (equal? . "==") (eq? . "is")
                           (quotient . "//") (modulo . "%") (expt . "**")
                           (and . "and") (or . "or")))])
    (values (car p) (cdr p))))

;; forms LE does not have: say so rather than compile them as calls
(define racket-forms
  '(let let* letrec let-values letrec-values cond when unless case do lambda
    define-syntax define-syntaxes define-for-syntax require provide quasiquote
    unquote syntax-rules match struct guard parameterize with-handlers))

;; a procedure the program names comes with the piece it needs
(define runtime-pieces
  (for/hash ([p (in-list '((list . list) (apply . apply) (keyword-apply . keyword-apply)
                           (object-ref . object-ref) (object-set! . object-set!)
                           (object-get-attr . object-get-attr)
                           (object-set-attr! . object-set-attr!)
                           (object-has-attr? . object-has-attr?)))])
    (values (car p) (cdr p))))

(define reserved
  '("False" "None" "True" "and" "as" "assert" "async" "await" "break" "class"
    "continue" "def" "del" "elif" "else" "except" "finally" "for" "from"
    "global" "if" "import" "in" "is" "lambda" "nonlocal" "not" "or" "pass"
    "raise" "return" "try" "while" "with" "yield"))

(define (munged sym)
  (define text
    (list->string
     (append*
      (for/list ([ch (in-string (symbol->string sym))])
        (case ch
          [(#\-) (string->list "_")] [(#\?) (string->list "_p")] [(#\!) (string->list "_b")]
          [else (list ch)])))))
  (define base (if (and (positive? (string-length text)) (char-numeric? (string-ref text 0)))
                   (string-append "_" text)
                   text))
  (if (member base reserved) (string-append base "_") base))

(define (py-string text)
  (string-append "\"" (string-join
                       (for/list ([ch (in-string text)])
                         (case ch
                           [(#\\) "\\\\"] [(#\") "\\\""] [(#\newline) "\\n"]
                           [(#\tab) "\\t"] [else (string ch)]))
                       "") "\""))

(define (py-datum value)
  (cond [(symbol? value) (error 'compile "a symbol is not data: ~a" value)]
        [(integer? value) (format "~a" value)]
        [(flonum? value) (format "~a" value)]
        [(string? value) (py-string value)]
        [(boolean? value) (if value "True" "False")]
        [(list? value) (format "[~a]" (string-join (map py-datum value) ", "))]
        [(vector? value) (format "(~a)" (string-join (map py-datum (vector->list value)) ", "))]
        [(hash? value)
         (format "{~a}" (string-join (for/list ([k (in-list (hash-keys value))])
                                       (format "~a: ~a" (py-datum k) (py-datum (hash-ref value k))))
                                     ", "))]
        [else (error 'compile "not data: ~a" value)]))

(define (head stx) (and (pair? (syntax->list stx)) (syntax-e (car (syntax->list stx)))))

(define (form-location stx)
  (define line (syntax-line stx))
  (if line
      (format "~a:~a:~a" (syntax-source stx) line (add1 (syntax-column stx)))
      "?"))

(define (not-le stx what)
  (error 'compile "~a: ~a: ~a" (form-location stx) what (syntax->datum stx)))

(define (statement-form? stx) (memq (head stx) '(define set!)))

;; the pieces a program asked for
(define needed (make-hash))
(define (need piece) (hash-set! needed piece #t))

(define (global-expr sym)
  (when (hash-ref infix sym #f)
    (error 'compile "an operator where a value belongs: ~a" sym))
  (when (hash-ref runtime-pieces sym #f) (need (hash-ref runtime-pieces sym)))
  (munged sym))

(define (indented text)
  (string-join (for/list ([line (in-list (string-split text "\n"))])
                 (string-append "    " line))
               "\n"))

;; a procedure that drives trampoline is emitted twice: it drives, and its body
;; holds the bounces, so a bounce never re-enters a driver
(define trampolined (make-hash))
(define (body-name sym) (string-append (munged sym) "_body"))

(define (mentions? stx sym)
  (cond [(identifier? stx) (eq? (syntax-e stx) sym)]
        [(not (syntax->list stx)) #f]
        [else (ormap (lambda (p) (mentions? p sym)) (syntax->list stx))]))

(define (scan-trampolined! stx)
  (define parts (syntax->list stx))
  (when parts
    (when (eq? (head stx) 'define)
      (define target (cadr parts))
      (define sig (and (pair? (syntax-e target)) (syntax-e target)))
      (when (and sig (ormap (lambda (b) (mentions? b 'trampoline)) (cddr parts)))
        (hash-set! trampolined (syntax-e (car sig)) #t)))
    (for ([p (in-list parts)]) (scan-trampolined! p))))

(define (expression stx)
  (if (statement-form? stx)
      (not-le stx "a statement where an expression belongs")
      (expr stx)))

;; only #f is false: 0, "" and '() are true, as they are in Racket
(define (lisp-true stx) (format "~a is not False" (expression stx)))

;; (f e* ...): more than one body is the begin the language has room for
(define (single bodies what [bounce? #f])
  (cond [(null? bodies) (error 'compile "~a: no body" what)]
        [(null? (cdr bodies)) (expr (car bodies) bounce?)]
        [else (begin-expr bodies bounce?)]))

(define (begin-expr bodies [bounce? #f])
  (need 'begin)
  (define last-index (sub1 (length bodies)))
  (format "_begin(~a)"
          (string-join (for/list ([e (in-list bodies)] [i (in-naturals)])
                         (if (= i last-index) (expr e bounce?) (expression e)))
                       ", ")))

;; what a bounce calls: the body of a trampolined procedure
(define (bounce-callee stx)
  (define f (car (syntax->list stx)))
  (define sym (and (identifier? f) (syntax-e f)))
  (if (and sym (hash-ref trampolined sym #f)) (body-name sym) (expr f)))

(define (tail-expr stx driver?)
  (if (and (not driver?) (eq? (head stx) 'trampoline))
      (single (cdr (syntax->list stx)) "trampoline" #t)
      (expression stx)))

(define (branch-expr stx bounce?)
  (if (statement-form? stx)
      (not-le stx "a statement where an expression belongs")
      (expr stx bounce?)))

(define (application stx bounce?)
  (define parts (syntax->list stx))
  (define f (car parts))
  (define args (cdr parts))
  (define name (and (identifier? f) (syntax-e f)))
  (cond [(memq (head stx) racket-forms) (not-le stx "a Racket form, not LE")]
        [(and name (hash-ref infix name #f) (>= (length args) 2))
         (format "(~a)" (string-join (map expression args) (format " ~a " (hash-ref infix name))))]
        [(and name (eq? name 'not) (= 1 (length args))) (format "(not ~a)" (expression (car args)))]
        [else
         (define call (format "~a(~a)" (if bounce? (bounce-callee stx) (expr f))
                              (string-join (map expression args) ", ")))
         (if bounce? (begin (need 'trampoline) (format "lambda: ~a" call)) call)]))

(define (expr stx [bounce? #f])
  (cond
    [(identifier? stx) (global-expr (syntax-e stx))]
    [(not (syntax->list stx)) (py-datum (syntax->datum stx))]
    [else
     (define parts (syntax->list stx))
     (case (head stx)
       [(quote)
        (when (not (= 2 (length parts))) (not-le stx "a quote takes one datum"))
        (py-datum (syntax->datum (cadr parts)))]
       [(if)
        (when (not (= 4 (length parts))) (not-le stx "an if takes three parts"))
        (format "(~a if ~a else ~a)"
                (branch-expr (caddr parts) bounce?) (lisp-true (cadr parts))
                (branch-expr (cadddr parts) bounce?))]
       [(begin) (begin-expr (cdr parts) bounce?)]
       [(raise)
        (when (not (= 2 (length parts))) (not-le stx "a raise takes one expression"))
        (need 'raise)
        (format "_raise(~a)" (expression (cadr parts)))]
       [(with-handler)
        (when (< (length parts) 3) (not-le stx "a with-handler takes a handler and a body"))
        (need 'with-handler)
        (format "_with_handler(~a, lambda: ~a)"
                (expression (cadr parts)) (single (cddr parts) "with-handler"))]
       [(trampoline)
        (need 'trampoline)
        (format "_trampoline(~a)" (single (cdr parts) "trampoline" #t))]
       [(lambda) (not-le stx "LE has no lambda: a procedure comes from define")]
       [else (application stx bounce?)])]))

(define (procedure-parts target)
  (define sig (syntax-e target))
  (define name (syntax-e (car sig)))
  (define (walk rest acc)
    (cond [(null? rest) (values (reverse acc) #f)]
          [(pair? rest) (walk (cdr rest) (cons (munged (syntax-e (car rest))) acc))]
          [else (values (reverse acc) (munged (syntax-e rest)))]))
  (define-values (params rest) (walk (cdr sig) '()))
  (values name params rest))

(define (params-text params rest)
  (string-join (append params (if rest (list (format "*~a" rest)) '())) ", "))

(define (body-lines forms tail-of)
  (append (for/list ([f (in-list (drop-right forms 1))]) (statement f))
          (list (format "return ~a" (tail-of (last forms))))))

(define (procedure-def name params rest forms tail-of)
  (define lines
    (append (if rest (begin (need 'list) (list (format "~a = list(~a)" rest rest))) '())
            (body-lines forms tail-of)))
  (string-append (format "def ~a(~a):\n" name (params-text params rest))
                 (indented (string-join lines "\n"))))

(define (statement s)
  (define parts (syntax->list s))
  (case (head s)
    [(define)
     (define target (cadr parts))
     (define bodies (cddr parts))
     (when (null? bodies) (not-le s "a definition needs a body"))
     (cond [(identifier? target)
            (when (not (null? (cdr bodies))) (not-le s "a value definition takes one expression"))
            (format "~a = ~a" (munged (syntax-e target)) (expression (car bodies)))]
           [(pair? (syntax-e target))
            (define-values (name params rest) (procedure-parts target))
            (cond [(hash-ref trampolined name #f)
                   (need 'trampoline)
                   (define bn (body-name name))
                   (string-append
                    (format "def ~a(~a):\n    return _trampoline(~a(~a))"
                            (munged name) (params-text params rest) bn (params-text params rest))
                    "\n\n"
                    (procedure-def bn params rest bodies (lambda (f) (tail-expr f #f))))]
                  [else (procedure-def (munged name) params rest bodies expression)])]
           [else (not-le s "a definition of what?")])]
    [(set!)
     (when (not (= 3 (length parts))) (not-le s "an assignment takes one expression"))
     (format "~a = ~a" (munged (syntax-e (cadr parts))) (expression (caddr parts)))]
    [(begin) (string-join (map statement (cdr parts)) "\n")]
    [(if)
     (when (not (= 4 (length parts))) (not-le s "an if takes three parts"))
     (string-append "if " (lisp-true (cadr parts)) ":\n"
                    (indented (statement (caddr parts))) "\n"
                    "else:\n" (indented (statement (cadddr parts))) "\n")]
    [else (expr s)]))

(define order
  '(begin raise trampoline with-handler list apply keyword-apply
    object-ref object-set! object-get-attr object-set-attr! object-has-attr?))

(define pieces
  (hasheq
   'begin (list "def _begin(*values):" "    return values[-1]")
   'raise (list "class _Raised(Exception):" "    def __init__(self, value):"
                "        super().__init__(value)" "        self.value = value" ""
                "def _raise(value):" "    raise _Raised(value)")
   'trampoline (list "def _trampoline(value):"
                     "    \"\"\"(trampoline e): call what the body returns while it is a procedure.\"\"\""
                     "    while callable(value):" "        value = value()" "    return value")
   'with-handler (list "def _with_handler(handler, body):"
                       "    \"\"\"(with-handler h e): the body, with h handling what it raises.\"\"\""
                       "    try:" "        return body()"
                       "    except _Raised as error:" "        return handler(error.value)"
                       "    except Exception as error:" "        return handler(error)")
   'list (list "_builtin_list = list" ""
               "def list(*items):" "    return _builtin_list(items)")
   'apply (list "def apply(function, *arguments):"
                "    return function(*arguments[:-1], *arguments[-1])")
   'keyword-apply (list "def keyword_apply(function, keyword_arguments, arguments):"
                        "    return function(*arguments, **keyword_arguments)")
   'object-ref (list "def object_ref(obj, key):" "    return obj[key]")
   'object-set! (list "def object_set_b(obj, key, value):" "    obj[key] = value")
   'object-get-attr (list "def object_get_attr(obj, name):" "    return getattr(obj, name)")
   'object-set-attr! (list "def object_set_attr_b(obj, name, value):" "    setattr(obj, name, value)")
   'object-has-attr? (list "def object_has_attr_p(obj, name):" "    return hasattr(obj, name)")))

(define (prelude)
  (define used (filter (lambda (piece) (hash-ref needed piece #f)) order))
  (string-join (for/list ([piece (in-list used)]) (string-join (hash-ref pieces piece) "\n"))
               "\n\n"))

;; the whole program: the pieces it asked for, then its statements
(define (compile-program forms)
  (hash-clear! needed)
  (hash-clear! trampolined)
  (for ([f (in-list forms)]) (scan-trampolined! f))
  (define body (string-join (for/list ([f (in-list forms)]) (statement f)) "\n\n"))
  (define prelude-text (prelude))
  (string-append header
                 (if (string=? prelude-text "") "" (string-append "\n" prelude-text "\n"))
                 "\n"
                 body
                 "\n"))
