#lang racket/base

(require racket/list
         racket/string)

;; LB -> Python.  LB is LL after the lift pass.
;;
;; LE is what #%python-code takes: Racket's s-expression syntax, statements and
;; expressions apart, procedures only through define, no macros, no symbols.
;;
;; A statement is what a body, a begin in statement position and the branch of a
;; statement if are made of; an expression is what an if, a call argument and a
;; begin in expression position are made of.  Nothing in an expression position
;; is a statement, so a definition cannot hide inside one and mean something
;; else there, and with-handler and trampoline are expressions like any other:
;; the handler runs where it stands, and a value position guards it.

(provide render-program)

(define header "# generated by rkt-pythonize\n")

;; names that read better as operators
(define infix
  (for/hash ([p (in-list '((+ . "+") (- . "-") (* . "*") (/ . "/")
                           (= . "==") (< . "<") (> . ">") (<= . "<=") (>= . ">=")
                           (equal? . "==") (eq? . "is")
                           (quotient . "//") (modulo . "%") (expt . "**")
                           (and . "and") (or . "or")))])
    (values (car p) (cdr p))))

;; forms LE does not have: say so rather than compile them as calls
(define racket-forms
  '(let let* letrec let-values letrec-values let*-values let-syntax letrec-syntax
    cond when unless case do lambda define-syntax define-syntaxes
    define-syntax-rule define-for-syntax begin-for-syntax define-values require
    provide quasiquote unquote unquote-splicing syntax-rules syntax-case
    syntax-parse match match-lambda struct guard parameterize with-handlers
    module module+ case-lambda))

;; a procedure the program names comes with the piece it needs
(define runtime-pieces
  (for/hash ([p (in-list '((list . list) (apply . apply) (keyword-apply . keyword-apply)
                           (object-ref . object-ref) (object-set! . object-set!)
                           (object-get-attr . object-get-attr)
                           (object-set-attr! . object-set-attr!)
                           (object-has-attr? . object-has-attr?)))])
    (values (car p) (cdr p))))

(define reserved
  '("False" "None" "True" "and" "as" "assert" "async" "await" "break" "class"
    "continue" "def" "del" "elif" "else" "except" "finally" "for" "from"
    "global" "if" "import" "in" "is" "lambda" "nonlocal" "not" "or" "pass"
    "raise" "return" "try" "while" "with" "yield"))

(define (munged sym)
  (define text
    (list->string
     (append*
      (for/list ([ch (in-string (symbol->string sym))])
        (case ch
          [(#\-) (string->list "_")] [(#\?) (string->list "_p")] [(#\!) (string->list "_b")]
          [else (list ch)])))))
  (define base (if (and (positive? (string-length text)) (char-numeric? (string-ref text 0)))
                   (string-append "_" text)
                   text))
  (if (member base reserved) (string-append base "_") base))

(define (py-string text)
  (string-append "\"" (string-join
                       (for/list ([ch (in-string text)])
                         (case ch
                           [(#\\) "\\\\"] [(#\") "\\\""] [(#\newline) "\\n"]
                           [(#\tab) "\\t"] [else (string ch)]))
                       "") "\""))

(define (py-datum value)
  (cond [(symbol? value) (error 'compile "a symbol is not data: ~a" value)]
        [(integer? value) (format "~a" value)]
        [(flonum? value) (format "~a" value)]
        [(string? value) (py-string value)]
        [(boolean? value) (if value "True" "False")]
        [(list? value) (format "[~a]" (string-join (map py-datum value) ", "))]
        [(vector? value) (format "(~a)" (string-join (map py-datum (vector->list value)) ", "))]
        [(hash? value)
         (format "{~a}" (string-join (for/list ([k (in-list (hash-keys value))])
                                       (format "~a: ~a" (py-datum k) (py-datum (hash-ref value k))))
                                     ", "))]
        [else (error 'compile "not data: ~a" value)]))

(define (head stx) (and (pair? (syntax->list stx)) (syntax-e (car (syntax->list stx)))))

(define (form-location stx)
  (define line (syntax-line stx))
  (if line
      (format "~a:~a:~a" (syntax-source stx) line (add1 (syntax-column stx)))
      "?"))

(define (not-le stx what)
  (error 'compile "~a: ~a: ~a" (form-location stx) what (syntax->datum stx)))

(define (statement-form? stx) (memq (head stx) '(define set!)))

;; the pieces a program asked for
(define needed (make-hash))
(define (need piece) (hash-set! needed piece #t))

;; Python names a program may lean on without defining them
(define builtins
  '("abs" "all" "any" "bin" "bool" "bytes" "callable" "chr" "dict" "dir"
    "divmod" "enumerate" "filter" "float" "format" "frozenset" "getattr"
    "hasattr" "hash" "hex" "id" "input" "int" "isinstance" "issubclass" "iter"
    "len" "list" "locals" "map" "max" "min" "next" "object" "oct" "open" "ord"
    "pow" "print" "range" "repr" "reversed" "round" "set" "setattr" "slice"
    "sorted" "str" "sum" "super" "tuple" "type" "vars" "zip"
    "ArithmeticError" "AssertionError" "AttributeError" "Exception"
    "IndexError" "KeyError" "NameError" "NotImplementedError" "OSError"
    "RuntimeError" "StopIteration" "TypeError" "ValueError" "ZeroDivisionError"))

;; a name the program never binds is a Python global, which is the point, but
;; it is worth saying so at warning level
(define warnings '())
(define (warn! message)
  (unless (member message warnings)
    (set! warnings (append warnings (list message)))))

;; lexically bound here, defined at the top of the program, a piece, an
;; operator, or a Python builtin?
(define (known-name? sym)
  (define name (munged sym))
  (or (ormap (lambda (scope) (and (member name scope) #t)) scopes)
      (and (member name module-names) #t)
      (hash-ref runtime-pieces sym #f)
      (hash-ref infix sym #f)
      (eq? sym 'not)
      (and (member name builtins) #t)))

(define (global-expr sym)
  (when (hash-ref infix sym #f)
    (error 'compile "an operator where a value belongs: ~a" sym))
  (when (hash-ref runtime-pieces sym #f) (need (hash-ref runtime-pieces sym)))
  (unless (known-name? sym)
    (warn! (format "no definition of ~a in this program: it becomes the Python name ~a"
                   sym (munged sym))))
  (munged sym))



;; the nonlocal and global declarations of the def being emitted
(define declarations '())

;; the names each enclosing procedure binds, innermost first, and the names the
;; program defines at the top level
(define scopes '())
(define module-names '())

(define (declare! line)
  (unless (member line declarations)
    (set! declarations (append declarations (list line)))))

(define (defined-name stx)
  (define target (cadr (syntax->list stx)))
  (if (identifier? target)
      (munged (syntax-e target))
      (munged (syntax-e (car (syntax-e target))))))

(define (collect-defined stx)
  (define parts (syntax->list stx))
  (cond [(not parts) '()]
        [(eq? (head stx) 'quote) '()]
        [(eq? (head stx) 'define)
         (cons (defined-name stx) (append* (map collect-defined (cddr parts))))]
        [else (append* (map collect-defined parts))]))

(define (collect-defined-in forms) (append* (map collect-defined forms)))

;; where a set! lands: a local name is assigned, a name an enclosing procedure
;; binds needs nonlocal, and a name the program defines at the top needs global
(define (assignment sym)
  (define name (munged sym))
  (unless (known-name? sym)
    (warn! (format "this program never defines ~a: this set! becomes a plain Python assignment"
                   name)))
  (cond [(null? scopes) name]
        [(member name (car scopes)) name]
        [(member name module-names)
         (declare! (format "global ~a" name))
         name]
        [else name]))





(define (indented text)
  (string-join (for/list ([line (in-list (string-split text "\n"))])
                 (string-append "    " line))
               "\n"))

(define (expression stx)
  (if (statement-form? stx)
      (not-le stx "a statement where an expression belongs")
      (expr stx)))

;; only #f is false: 0, "" and '() are true, as they are in Racket
(define (lisp-true stx) (format "~a is not False" (expression stx)))


(define (begin-expr bodies)
  (need 'begin)
  (format "_begin(~a)" (string-join (map expression bodies) ", ")))


(define (application stx)
  (define parts (syntax->list stx))
  (define f (car parts))
  (define args (cdr parts))
  (define name (and (identifier? f) (syntax-e f)))
  (cond [(memq (head stx) racket-forms) (not-le stx "a Racket form, not LE")]
        [(and name (hash-ref infix name #f) (>= (length args) 2))
         (format "(~a)" (string-join (map expression args) (format " ~a " (hash-ref infix name))))]
        [(and name (eq? name 'not) (= 1 (length args))) (format "(not ~a)" (expression (car args)))]
        [else
         (define callee (if (eq? (head f) 'lambda) (format "(~a)" (expr f)) (expr f)))
         (format "~a(~a)" callee (string-join (map expression args) ", "))]))

(define (expr stx)
  (cond
    [(identifier? stx) (global-expr (syntax-e stx))]
    [(not (syntax->list stx)) (py-datum (syntax->datum stx))]
    [else
     (define parts (syntax->list stx))
     (case (head stx)
       [(quote)
        (when (not (= 2 (length parts))) (not-le stx "a quote takes one datum"))
        (py-datum (syntax->datum (cadr parts)))]
       [(if)
        (when (not (= 4 (length parts))) (not-le stx "an if takes three parts"))
        (format "(~a if ~a else ~a)"
                (expression (caddr parts)) (lisp-true (cadr parts))
                (expression (cadddr parts)))]
       [(begin) (begin-expr (cdr parts))]
       [(raise)
        (when (not (= 2 (length parts))) (not-le stx "a raise takes one expression"))
        (need 'raise)
        (format "_raise(~a)" (expression (cadr parts)))]
       [(with-handler)
        (when (not (= 3 (length parts))) (not-le stx "a with-handler takes a handler and a body"))
        (need 'with-handler)
        (format "_with_handler(~a, ~a)" (expression (cadr parts)) (expression (caddr parts)))]
       [(trampoline)
        (when (not (= 2 (length parts))) (not-le stx "a trampoline takes the function to call"))
        (need 'trampoline)
        (format "_trampoline(~a)" (expression (cadr parts)))]
       [(lambda)
        (when (not (= 3 (length parts)))
          (not-le stx "a lambda takes a parameter list and one expression"))
        (define sig (syntax-e (cadr parts)))
        (when (not (or (null? sig) (pair? sig)))
          (not-le stx "a lambda takes a parameter list"))
        (define-values (params rest) (split-params sig))
        (define saved-scopes scopes)
        (set! scopes (cons (append params (if rest (list rest) '())) scopes))
        (define body (expression (caddr parts)))
        (set! scopes saved-scopes)
        (if (null? params)
            (format "lambda: ~a" body)
            (format "lambda ~a: ~a" (params-text params rest) body))]
       [else (application stx)])]))

;; (x y ...) or (x y ... . rest): the munged parameters and the rest parameter
(define (split-params lst)
  (define (walk rest acc)
    (cond [(null? rest) (values (reverse acc) #f)]
          [(pair? rest) (walk (cdr rest) (cons (munged (syntax-e (car rest))) acc))]
          [else (values (reverse acc) (munged (syntax-e rest)))]))
  (walk lst '()))

(define (procedure-parts target)
  (define sig (syntax-e target))
  (define name (syntax-e (car sig)))
  (define-values (params rest) (split-params (cdr sig)))
  (values name params rest))

(define (params-text params rest)
  (string-join (append params (if rest (list (format "*~a" rest)) '())) ", "))

(define (body-lines forms)
  (define earlier (for/list ([f (in-list (drop-right forms 1))]) (statement f)))
  (define last-form (last forms))
  (append earlier
          (list (if (statement-form? last-form)
                    ;; a body is a sequence of statements: one that ends in a
                    ;; statement, as a setter does, has no value to return
                    (string-append (statement last-form) "\nreturn None")
                    (format "return ~a" (expression last-form))))))

(define (procedure-def name params rest forms)
  (define saved-declarations declarations)
  (define saved-scopes scopes)
  (set! declarations '())
  (set! scopes (cons (append params (if rest (list rest) '()) (collect-defined-in forms))
                     scopes))
  (define lines
    ;; a rest parameter is a list, and the LE list is not Python's
    (append (if rest (list (format "~a = [*~a]" rest rest)) '())
            (body-lines forms)))
  (define declarations-text (reverse declarations))
  (set! declarations saved-declarations)
  (set! scopes saved-scopes)
  (string-append (format "def ~a(~a):\n" name (params-text params rest))
                 (indented (string-join (append declarations-text lines) "\n"))))


(define (statement s)
  (define parts (syntax->list s))
  (case (head s)
    [(define)
     (define target (cadr parts))
     (define bodies (cddr parts))
     (when (null? bodies) (not-le s "a definition needs a body"))
     (cond [(identifier? target)
            (when (not (null? (cdr bodies))) (not-le s "a value definition takes one expression"))
            (format "~a = ~a" (munged (syntax-e target)) (expression (car bodies)))]
           [(pair? (syntax-e target))
            (define-values (name params rest) (procedure-parts target))
            (procedure-def (munged name) params rest bodies)]
           [else (not-le s "a definition of what?")])]
    [(set!)
     (when (not (= 3 (length parts))) (not-le s "an assignment takes one expression"))
     (format "~a = ~a" (assignment (syntax-e (cadr parts))) (expression (caddr parts)))]
    [(begin) (string-join (map statement (cdr parts)) "\n")]
    [(if)
     (when (not (= 4 (length parts))) (not-le s "an if takes three parts"))
     (string-append "if " (lisp-true (cadr parts)) ":\n"
                    (indented (statement (caddr parts))) "\n"
                    "else:\n" (indented (statement (cadddr parts))) "\n")]
    [else (expr s)]))

(define order
  '(begin raise trampoline with-handler list apply keyword-apply
    object-ref object-set! object-get-attr object-set-attr! object-has-attr?))

(define pieces
  (hasheq
   'begin (list "def _begin(*values):" "    return values[-1]")
   'raise (list "class _Raised(Exception):" "    def __init__(self, value):"
                "        super().__init__(value)" "        self.value = value" ""
                "def _raise(value):" "    raise _Raised(value)")
   'trampoline (list "def _trampoline(value):"
                     "    \"\"\"(trampoline e): call what the body returns while it is a procedure.\"\"\""
                     "    while callable(value):" "        value = value()" "    return value")
   'with-handler (list "def _with_handler(handler, body):"
                       "    \"\"\"(with-handler h e): the body, with h handling what it raises.\"\"\""
                       "    try:" "        return body()"
                       "    except _Raised as error:" "        return handler(error.value)"
                       "    except Exception as error:" "        return handler(error)")
   'list (list "_builtin_list = list" ""
               "def list(*items):" "    return _builtin_list(items)")
   'apply (list "def apply(function, *arguments):"
                "    return function(*arguments[:-1], *arguments[-1])")
   'keyword-apply (list "def keyword_apply(function, keyword_arguments, arguments):"
                        "    return function(*arguments, **keyword_arguments)")
   'object-ref (list "def object_ref(obj, key):" "    return obj[key]")
   'object-set! (list "def object_set_b(obj, key, value):" "    obj[key] = value")
   'object-get-attr (list "def object_get_attr(obj, name):" "    return getattr(obj, name)")
   'object-set-attr! (list "def object_set_attr_b(obj, name, value):" "    setattr(obj, name, value)")
   'object-has-attr? (list "def object_has_attr_p(obj, name):" "    return hasattr(obj, name)")))

(define (prelude)
  (define used (filter (lambda (piece) (hash-ref needed piece #f)) order))
  (string-join (for/list ([piece (in-list used)]) (string-join (hash-ref pieces piece) "\n"))
               "\n\n"))

;; the whole program: the pieces it asked for, then its statements
(define (render-program forms)
  (hash-clear! needed)
  (set! declarations '())
  (set! scopes '())
  (set! warnings '())
  (set! module-names
        (for/list ([f (in-list forms)] #:when (eq? (head f) 'define)) (defined-name f)))
  (define body (string-join (for/list ([f (in-list forms)]) (statement f)) "\n\n"))
  (define prelude-text (prelude))
  (for ([message (in-list warnings)])
    (log-warning "rkt-pythonize: ~a" message))
  (string-append header
                 (if (string=? prelude-text "") "" (string-append "\n" prelude-text "\n"))
                 "\n"
                 body
                 "\n"))
