#lang racket/base

(require racket/list
         racket/string
         "names.rkt"
         "params.rkt")

;; LB -> Python.  LB is LL after the lift pass.
;;
;; LE is what #%python-code takes: Racket's s-expression syntax, statements and
;; expressions apart, procedures only through define, no macros, no symbols.
;;
;; A statement is what a body, a begin in statement position and the branch of a
;; statement if are made of; an expression is what an if, a call argument and a
;; begin in expression position are made of.  Nothing in an expression position
;; is a statement, so a definition cannot hide inside one and mean something
;; else there, and with-handler and trampoline are expressions like any other:
;; the handler runs where it stands, and a value position guards it.

;; the scope check needs to know what a Python program can call by itself
(provide render-program)

(define header "# generated by rkt-pythonize\n")

;; names that read better as operators


;; a procedure the program names comes with the piece it needs



(define (py-string text)
  (string-append "\"" (string-join
                       (for/list ([ch (in-string text)])
                         (case ch
                           [(#\\) "\\\\"] [(#\") "\\\""] [(#\newline) "\\n"]
                           [(#\tab) "\\t"] [else (string ch)]))
                       "") "\""))

(define (py-datum value)
  (cond [(symbol? value) (error 'compile "a symbol is not data: ~a" value)]
        [(keyword? value) (error 'compile "a keyword is not data: ~a" value)]
        [(integer? value) (format "~a" value)]
        [(flonum? value) (format "~a" value)]
        [(string? value) (py-string value)]
        [(boolean? value) (if value "True" "False")]
        [(list? value) (format "[~a]" (string-join (map py-datum value) ", "))]
        [(vector? value) (format "(~a)" (string-join (map py-datum (vector->list value)) ", "))]
        [(hash? value)
         (format "{~a}" (string-join (for/list ([k (in-list (hash-keys value))])
                                       (format "~a: ~a" (py-datum k) (py-datum (hash-ref value k))))
                                     ", "))]
        [else (error 'compile "not data: ~a" value)]))

(define (head stx) (and (pair? (syntax->list stx)) (syntax-e (car (syntax->list stx)))))

(define (form-location stx)
  (define line (syntax-line stx))
  (if line
      (format "~a:~a:~a" (syntax-source stx) line (add1 (syntax-column stx)))
      "?"))

(define (not-le stx what)
  (error 'compile "~a: ~a: ~a" (form-location stx) what (syntax->datum stx)))


;; the pieces a program asked for
;; a piece may need another: with-handler catches the exception raise defines
(define piece-dependencies (hash 'with-handler '(raise)))

(define needed (make-hash))
(define (need piece)
  (unless (hash-ref needed piece #f)
    (hash-set! needed piece #t)
    (for ([needed-piece (in-list (hash-ref piece-dependencies piece '()))])
      (need needed-piece))))

;; an operator is syntax: what it renders to depends on how many operands it
;; has, and it is never a value
(define (operator-text name args)
  (define (arity)
    (error 'compile "~a takes ~a operands" name (length args)))
  (cond [(and (eq? name 'not) (= 1 (length args))) (format "(not ~a)" (expr (car args)))]
        [(and (hash-ref prefix name #f) (= 1 (length args)))
         (if (eq? name '+) (expr (car args))
             (format "(~a~a)" (hash-ref prefix name) (expr (car args))))]
        [(and (hash-ref infix name #f) (>= (length args) 2))
         (format "(~a)" (string-join (map expr args) (format " ~a " (hash-ref infix name))))]
        [else (arity)]))

(define (global-expr sym)
  (when (memq sym operators)
    (error 'compile "an operator where a value belongs: ~a" sym))
  ;; a piece the compiler calls itself, and a piece the program calls: the
  ;; second is the program's own name where the program binds it, and the
  ;; prelude's, under the prefix it carries, everywhere else
  (define called (called-piece sym))
  (cond [called (need called) (piece-name called)]
        [(and (hash-ref runtime-pieces sym #f) (not (bound-name? (python-name sym))))
         (need (hash-ref runtime-pieces sym))
         (piece-name sym)]
        [else (python-name sym)]))

;; a name the program binds, at the top level or in a procedure around here
(define (bound-name? name)
  (or (and (member name module-names) #t)
      (for/or ([scope (in-list scopes)]) (and (member name scope) #t))))



;; the nonlocal and global declarations of the def being emitted
(define declarations '())

;; the names each enclosing procedure binds, innermost first, and the names the
;; program defines at the top level
(define scopes '())
(define module-names '())

(define (declare! line)
  (unless (member line declarations)
    (set! declarations (append declarations (list line)))))

(define (defined-name stx)
  (define target (cadr (syntax->list stx)))
  (if (identifier? target)
      (python-name (syntax-e target))
      (python-name (syntax-e (car (syntax-e target))))))

(define (collect-defined stx)
  (define parts (syntax->list stx))
  (cond [(not parts) '()]
        [(eq? (head stx) 'quote) '()]
        [(eq? (head stx) 'define)
         (cons (defined-name stx) (append* (map collect-defined (cddr parts))))]
        [else (append* (map collect-defined parts))]))

(define (collect-defined-in forms) (append* (map collect-defined forms)))

;; where a set! lands: a local name is assigned, a name an enclosing procedure
;; binds needs nonlocal, and a name the program defines at the top needs global
(define (assignment sym)
  (define name (python-name sym))
  (cond [(null? scopes) name]
        [(member name (car scopes)) name]
        [(member name module-names)
         (declare! (format "global ~a" name))
         name]
        [else name]))





(define (indented text)
  (string-join (for/list ([line (in-list (string-split text "\n"))])
                 (string-append "    " line))
               "\n"))


;; only #f is false: 0, "" and '() are true, as they are in Racket
(define (lisp-true stx) (format "~a is not False" (expr stx)))


(define (begin-expr bodies)
  (need 'begin)
  (format "~a(~a)" (piece-name 'begin) (string-join (map expr bodies) ", ")))


(define (application stx)
  (define parts (syntax->list stx))
  (define f (car parts))
  (define args (cdr parts))
  (define name (and (identifier? f) (syntax-e f)))
  (cond [(and name (memq name operators)) (operator-text name args)]
        [else
         (define callee (if (eq? (head f) 'lambda) (format "(~a)" (expr f)) (expr f)))
         ;; the positional arguments first, then the keyword ones: Python's
         ;; order, and the order it evaluates them in
         (define-values (positional keywords)
           (argument-parts args (lambda (message) (not-le stx message))))
         (format "~a(~a)"
                 callee
                 (string-join (append (map expr positional)
                                      (for/list ([keyword (in-list keywords)])
                                        (format "~a=~a"
                                                (python-keyword-name (car keyword))
                                                (expr (cadr keyword)))))
                              ", "))]))

(define (expr stx)
  (cond
    [(identifier? stx) (global-expr (syntax-e stx))]
    [(not (syntax->list stx)) (py-datum (syntax->datum stx))]
    [else
     (define parts (syntax->list stx))
     (case (head stx)
       [(quote)
        (when (not (= 2 (length parts))) (not-le stx "a quote takes one datum"))
        (py-datum (syntax->datum (cadr parts)))]
       [(if)
        (when (not (= 4 (length parts))) (not-le stx "an if takes three parts"))
        (format "(~a if ~a else ~a)"
                (expr (caddr parts)) (lisp-true (cadr parts))
                (expr (cadddr parts)))]
       [(begin) (begin-expr (cdr parts))]
       [(raise)
        (when (not (= 2 (length parts))) (not-le stx "a raise takes one expression"))
        (need 'raise)
        (format "~a(~a)" (piece-name 'raise) (expr (cadr parts)))]
       [(import)
        (when (not (= 2 (length parts))) (not-le stx "an import takes one module"))
        (need 'import)
        ;; a name names its own module; a string or an expression is the name
        (format "~a(~a)" (piece-name 'import)
                (if (identifier? (cadr parts))
                    (py-string (symbol->string (syntax-e (cadr parts))))
                    (expr (cadr parts))))]
       [(with-handler)
        (when (not (= 3 (length parts))) (not-le stx "a with-handler takes a handler and a body"))
        (need 'with-handler)
        (format "~a(~a, ~a)" (piece-name 'with-handler) (expr (cadr parts)) (expr (caddr parts)))]
       [(trampoline)
        (when (not (= 2 (length parts))) (not-le stx "a trampoline takes the function to call"))
        (need 'trampoline)
        (format "~a(~a)" (piece-name 'trampoline) (expr (cadr parts)))]
       [(lambda)
        (when (not (= 3 (length parts)))
          (not-le stx "a lambda takes a parameter list and one expression"))
        (define sig (syntax->datum (cadr parts)))
        (when (not (or (null? sig) (pair? sig)))
          (not-le stx "a lambda takes a parameter list"))
        (define-values (params keywords rest) (signature-parts sig))
        (define saved-scopes scopes)
        (set! scopes (cons (signature-names params keywords rest) scopes))
        (define body (expr (caddr parts)))
        (set! scopes saved-scopes)
        (if (and (null? params) (null? keywords))
            (format "lambda: ~a" body)
            (format "lambda ~a: ~a" (params-text params keywords rest) body))]
       [else (application stx)])]))

;; (x y #:k k . rest): a signature is core/params.rkt's, and a name is
;; core/names.rkt's
;; where it is written
(define (procedure-parts target)
  (define sig (syntax->datum target))
  (define name (car sig))
  (define-values (params keywords rest) (signature-parts (cdr sig)))
  (values name params keywords rest))

;; every Python name a signature binds
(define (signature-names params keywords rest)
  (append (map python-name params)
          (map (lambda (k) (python-keyword-name (keyword-param-keyword k))) keywords)
          (if rest (list (python-name rest)) '())))

;; def f(a, b, *rest, k): the star is what makes a keyword parameter
;; keyword-only, as it is in Racket, and it stands where the rest parameter
;; would
(define (params-text params keywords rest)
  (define positional (map python-name params))
  (define star (cond [rest (list (format "*~a" (python-name rest)))]
                     [(pair? keywords) (list "*")]
                     [else '()]))
  (define keyword-params
    (for/list ([k (in-list keywords)]) (python-keyword-name (keyword-param-keyword k))))
  (string-join (append positional star keyword-params) ", "))

;; check-expression has said that the last form of a body is an expression
(define (body-lines forms)
  (append (for/list ([f (in-list (drop-right forms 1))]) (statement f))
          (list (format "return ~a" (expr (last forms))))))

(define (procedure-def name params keywords rest forms)
  (define saved-declarations declarations)
  (define saved-scopes scopes)
  (set! declarations '())
  (set! scopes (cons (append (signature-names params keywords rest)
                             (collect-defined-in forms))
                     scopes))
  (define lines
    ;; a rest parameter is a list, and the LE list is not Python's
    (append (if rest (list (format "~a = [*~a]" (python-name rest) (python-name rest))) '())
            (body-lines forms)))
  (define declarations-text (reverse declarations))
  (set! declarations saved-declarations)
  (set! scopes saved-scopes)
  (string-append (format "def ~a(~a):\n" name (params-text params keywords rest))
                 (indented (string-join (append declarations-text lines) "\n"))))


(define (statement s)
  (define parts (syntax->list s))
  (case (head s)
    [(define)
     (define target (cadr parts))
     (define bodies (cddr parts))
     (when (null? bodies) (not-le s "a definition needs a body"))
     (cond [(identifier? target)
            (when (not (null? (cdr bodies))) (not-le s "a value definition takes one expression"))
            (format "~a = ~a" (python-name (syntax-e target)) (expr (car bodies)))]
           [(pair? (syntax-e target))
            (define-values (name params keywords rest) (procedure-parts target))
            (procedure-def (python-name name) params keywords rest bodies)]
           [else (not-le s "a definition of what?")])]
    [(set!)
     (when (not (= 3 (length parts))) (not-le s "an assignment takes one expression"))
     (format "~a = ~a" (assignment (syntax-e (cadr parts))) (expr (caddr parts)))]
    [(begin) (string-join (map statement (cdr parts)) "\n")]
    [(if)
     (when (not (= 4 (length parts))) (not-le s "an if takes three parts"))
     (string-append "if " (lisp-true (cadr parts)) ":\n"
                    (indented (statement (caddr parts))) "\n"
                    "else:\n" (indented (statement (cadddr parts))) "\n")]
    [else (expr s)]))



(define (prelude)
  (define used (filter (lambda (piece) (hash-ref needed piece #f)) piece-order))
  (string-join (for/list ([piece (in-list used)]) (piece-text piece))
               "\n\n"))

;; core/names.rkt names a piece: ~a in its text is where its own name goes --
;; a piece that answers to an LE name follows the style of the moment -- and ~t
;; is where the prelude's prefix goes, for the names it keeps inside itself
(define (piece-text piece)
  (define name (piece-name piece))
  (define prefix (prelude-prefix))
  (string-join (for/list ([line (in-list (hash-ref pieces piece))])
                 (string-replace (string-replace line "~t" prefix) "~a" name))
               "\n"))

;; the whole program: the pieces it asked for, then its statements
(define (render-program forms)
  (hash-clear! needed)
  (set! declarations '())
  (set! scopes '())
  (set! module-names
        (for/list ([f (in-list forms)] #:when (eq? (head f) 'define)) (defined-name f)))
  (define body (string-join (for/list ([f (in-list forms)]) (statement f)) "\n\n"))
  (define prelude-text (prelude))
  (string-append header
                 (if (string=? prelude-text "") "" (string-append "\n" prelude-text "\n"))
                 "\n"
                 body
                 "\n"))
