#lang scribble/manual

@; README.md is generated from this file: run ./build-docs.sh after editing.
@; The README is also the first chapter of the manual: rkt-pythonize.scrbl
@; pulls this file in with @include-section.

@require[@for-label[rkt-pythonize
                    racket/base]]

@; @codeblock lexes its content as Racket, which mangles the pipes in the
@; grammar below and the # comments in the Python, so a block of text that is
@; not Racket is typeset as a boxed block instead.  The spaces are made
@; non-breaking because the Markdown backend breaks a line of text at 72
@; characters and only at a plain space; both backends show them as spaces.
@(define (plain-code . lines)
   (tabular #:style 'boxed
            (list (list (apply verbatim
                               (for/list ([line (in-list lines)])
                                 (regexp-replace* #rx" " line "\u00A0")))))))

@title[#:style 'unnumbered]{README}

An LE-to-Python compiler behind one macro.

@tt{rkt-pythonize} is a library, and it exports one macro:
@racket[#%python-code].  The Python that its body compiles to @italic{is} the
value of the macro, and the compilation happens at expansion time, so the value
is a string:

@codeblock|{
#lang racket/base
(require rkt-pythonize)

(define python
  (#%python-code
    (define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
    (print (fact 5))))

(displayln python)
}|

@plain-code|{
# generated by rkt-pythonize

def fact(n):
    return (1 if (n == 0) is not False else (n * fact((n - 1))))

print(fact(5))
}|

Nothing else is exported: there is no @tt{#lang}, no reader, no command line,
and no Racket form is redefined or shadowed.  The macro is the whole interface.

@section[#:style 'unnumbered]{Pipeline}

@racket[#%python-code] runs five passes, and only the last one writes Python:

@; the tables are hand-aligned text in a boxed block: the Markdown backend has no
@; table, and its flattened one runs cells together where a cell fills a column
@plain-code|{
pass                        in    out     what it does
core/check-expression.rkt   LE    LE      refuses a statement where an expression belongs, and a Racket form that is not LE
core/check-scope.rkt        LE    LE      logs a warning for a name the program never binds
core/explicit.rkt           LE    LL      a form that takes a thunk gets an explicit lambda
core/lift.rkt               LL    LB      every procedure becomes a top-level define that takes what it captures
core/render.rkt             LB    Python  the source, with the pieces the program asked for
}|

The names a Python program has without the source defining them live in
@tt{core/names.rkt} as two parameters: @racket[runtime-names] (the pieces and
operators LE may use) and @racket[python-builtins] (the Python names a lifted
program may call).  Widen either before a module's @racket[#%python-code] forms
and the scope check stops warning about what you added:

@codeblock|{
(begin-for-syntax (runtime-names (cons 'sys (runtime-names))))
}|

@section[#:style 'unnumbered]{LE}

Inside @racket[#%python-code] the language is LE, a small Lisp in Racket's
s-expression syntax.  A statement is what a body, a @racket[begin] in statement
position and the branch of a statement @racket[if] are made of; an expression is
what an @racket[if], a call argument and a @racket[begin] in expression position
are made of.  Nothing in an expression position is a statement, so a definition
cannot hide inside one and mean something else there, and
@racket[with-handler] and @racket[trampoline] are expressions like any other:
the handler runs where it stands, and a value position guards it.

@plain-code|{
s ::= e                                  an expression, for its value or its effect
    | (define x e)                       bind a value
    | (define (x x* ...) s* ...)         bind a procedure
    | (define (x x* ... . rest) s* ...)  bind a procedure; the rest parameter
    |                                    collects the arguments into a list
    | (set! x e)                         assign
    | (begin s ...)                      a sequence, of statements here
    | (if e1 s1 s2)                      a conditional of statements

e ::= x                                  variable, a Python global
    | l                                  self-evaluating literal
    | 'd                                 quoted datum
    | (import x)                          the module the name or string x names
    | (lambda (x* ...) s* ...)           a procedure, lifted like a define
    | (if e1 e2 e3)                      conditional
    | (begin e1 e* ...)                  a sequence, of expressions here
    | (raise e1)                         raise an exception
    | (with-handler e1 s* ...)           run the body with e1 handling what it raises
    | (trampoline s* ... e)              call what the last body returns while it is a procedure
    | (e0 e* ...)                        application

d ::= int | float | string | boolean | list | tuple | dict
l ::= int | float | string | boolean | tuple | dict
}|

A procedure body is a sequence of statements, and its value is the last
expression in it.  The body of a @racket[with-handler] or a @racket[trampoline]
is a statement sequence too: when it holds @racket[define] or @racket[set!] it
becomes a nested @racket[def] that runs where the form stands, and a lone
expression stays an inline @racket[lambda].  A @racket[trampoline] ends with the
expression whose value it calls.

@racket[set!] of a name the program defines at the top level becomes
@racket[global]; @racket[set!] of a name the program never defines is a plain
Python assignment, and the compiler says so.  A procedure that @racket[set!]s a
variable it captures is a compile error: a lifted procedure receives what it
captures as parameters, so there is nothing to assign to.  A capture that is
shadowed where the procedure is used is a compile error too -- rename one of the
two.

@racket[lambda] takes the same parameter lists as @racket[define] -- a rest
parameter included, and it collects into a list -- and its body is a statement
sequence like a procedure body, with the value of its last expression.

@section[#:style 'unnumbered]{Data}

@racket[quote] is data: integers, floats, strings, booleans, lists, tuples and
dicts.  A list is a Python list, a tuple is @racket[#(1 2)] and becomes
@tt{(1, 2)}, and a dict is @racket[#hash(("a" . 1))] and becomes @tt{{"a": 1}},
so dict keys are strings.  There is no symbol type, so quoting a symbol is a
compile error, and there is no @racket[eval] and no @racket[gensym].

@section[#:style 'unnumbered]{Names}

@itemlist[
@item{A free identifier is a Python global: @racket[(print (len "abc"))]
becomes @tt{print(len("abc"))}.}
@item{Names are munged into readable Python identifiers: @racket[even?] is
@tt{even_p}, @racket[set-car!] is @tt{set_car_b}, @racket[object-ref] is
@tt{object_ref}, and a name that is a Python keyword gets a trailing @tt{_}.}
@item{Operators are @bold{syntax}, not procedures.  With two or more operands
they are infix: @tt{+ - * / quotient modulo expt}, @tt{& | ^ << >>},
@tt{= not= < > <= >=} (@racket[equal?] is @tt{=}, @racket[eq?] is @tt{is}),
@racket[in], @racket[and], @racket[or].  With one operand @racket[not], @tt{-}
and @tt{~} are prefix, and @racket[(+ x)] is @racket[x].  An operator is never
a value: @racket[(apply + xs)] and @racket[(print +)] are refused, so define a
procedure when the procedure itself is wanted.}
@item{A name the program never binds is a Python global, which is the point, but
the compiler logs a warning about it: a reference to a name no @racket[define]
or parameter binds, and a @racket[set!] of one.  Python builtins (@racket[print],
@racket[len], ...) and the pieces below are known, so they stay quiet.  The
warnings are logged at warning level, so @tt{PLTSTDERR=warning} is how you see
them.}
@item{A procedure the program names comes with the piece it needs, and nothing
else does.  The pieces are exactly:}]

@plain-code|{
source                          Python
(raise e)                       _raise, _Raised
(with-handler h e ...)          _with_handler
(trampoline s* ... e)           _trampoline
begin in an expression          _begin
(import x)                      import_module
(list 1 2)                      list
(apply f xs)                    apply
(keyword-apply f kw xs)         keyword_apply
(object-ref xs 0)               object_ref
(object-set! xs 0 1)            object_set_b
(object-get-attr xs "append")   object_get_attr
(object-set-attr! xs "a" 1)     object_set_attr_b
(object-has-attr? xs "append")  object_has_attr_p
}|

@section[#:style 'unnumbered]{Truth and tail calls}

Only @racket[#f] is false.  An @racket[if] compiles to
@tt{(then if test is not False else else)}, so @tt{0}, @tt{""} and
@racket[(quote ())] are true, as they are in Racket; @racket[and], @racket[or]
and @racket[not] are Python's operators and keep Python's truth.

Tail calls are explicit.  @racket[trampoline] calls what its last body returns,
and keeps calling while that value is a procedure, so a procedure that returns a
thunk for its tail call loops flat and one that returns anything else is done.
Nothing is recognised for you: the compiler does not look for a tail call and
does not wrap one, so the thunk is yours to write.

@codeblock|{
(define python
  (#%python-code
    (define (count n acc)
      (if (= n 0) acc (lambda () (count (- n 1) (+ acc 1)))))
    (print (trampoline (count 100000 0)))))

(displayln python)     ; the Python source; running it prints 100000
}|

@section[#:style 'unnumbered]{Macros and reaching outside}

LE has no macros, because a Racket macro is the better place for sugar: write
the sugar in Racket and let it expand to @racket[#%python-code], or build the LE
forms as data and hand them to the macro:

@codeblock|{
(define-syntax-rule (python-twice e) (#%python-code (print e) (print e)))
(displayln (python-twice (quote (1 2))))
;; the source it renders is print([1, 2]) twice, so running it prints two lines
}|

There is no @racket[#%python-code] at run time: it is expanded away, and what a
program does with the string is up to it.

@tt{CHANGELOG.md} says what changed in each version.  Both @tt{README.md} and
@tt{CHANGELOG.md} are generated: edit @tt{scribblings/readme.scrbl} and
@tt{scribblings/changelog.scrbl}, then run @tt{./build-docs.sh}.

@section[#:style 'unnumbered]{Tests}

@codeblock|{
$ PLTCOLLECTS="$PWD/..:" TMPDIR="$PWD/.tmp" raco test tests/
}|

The tests use the macro directly, look at the Python it renders, and run it with
@tt{python3}.  @tt{PLTCOLLECTS} is only needed when an older copy of the package
is installed; with the package installed, @tt{raco test -x -p rkt-pythonize} is
enough.

@section[#:style 'unnumbered]{Layout}

@codeblock|{
main.rkt                     the library: #%python-code
core/check-expression.rkt    LE -> LE: statement/expression context
core/check-scope.rkt         LE -> LE: lexical scope and warnings
core/explicit.rkt            LE -> LL: make-explicit
core/lift.rkt                LL -> LB: procedures lifted to the top level
core/render.rkt              LB -> Python
tests/dsl.rkt                end-to-end tests
scribblings/rkt-pythonize.scrbl  the manual
scribblings/readme.scrbl     the README, also the manual's first chapter
scribblings/changelog.scrbl  the changelog, also the manual's last chapter
build-docs.sh                renders both into README.md and CHANGELOG.md
CHANGELOG.md                 what changed in each version
}|

@section[#:style 'unnumbered]{Design notes}

@itemlist[
@item{Clojure is the inspiration for the shape of the compiler, not for the
syntax: one small compiler instead of a pipeline of passes, no CPS, and
generated Python that stays readable.}
@item{One macro, five passes, and the pipeline they form is at the top of this
file.  Nothing is replaced and nothing is wrapped; the only thing the library
knows about Racket is how to be a macro.}
@item{There is no separate @tt{core.py} and no runtime library beyond the pieces
above.}
@item{@tt{raco setup rkt-pythonize} builds the manual.}]

@section[#:style 'unnumbered]{License}

Apache-2.0 OR MIT.
