#lang scribble/manual

@; README.md is generated from this file: run ./build-docs.sh after editing.
@; The README is also the first chapter of the manual: rkt-pythonize.scrbl
@; pulls this file in with @include-section.

@require[@for-label[rkt-pythonize
                    racket/base]]

@; @codeblock lexes its content as Racket, which mangles the pipes in the
@; grammar below and the # comments in the Python, so a block of text that is
@; not Racket is typeset as a boxed block instead.  The spaces are made
@; non-breaking because the Markdown backend breaks a line of text at 72
@; characters and only at a plain space; both backends show them as spaces.
@(define (plain-code . lines)
   (tabular #:style 'boxed
            (list (list (apply verbatim
                               (for/list ([line (in-list lines)])
                                 (regexp-replace* #rx" " line "\u00A0")))))))

@title[#:style 'unnumbered]{README}

An LE-to-Python compiler behind one macro.

@tt{rkt-pythonize} is a library, and it exports one macro:
@racket[#%python-code].  The Python that its body compiles to @italic{is} the
value of the macro, and the compilation happens at expansion time, so the value
is a string:

@codeblock|{
#lang racket/base
(require rkt-pythonize)

(define python
  (#%python-code
    (define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
    (print (fact 5))))

(displayln python)
}|

@plain-code|{
# generated by rkt-pythonize

def fact(n):
    return (1 if (n == 0) is not False else (n * fact((n - 1))))

print(fact(5))
}|

Nothing else is exported: there is no @tt{#lang}, no reader, no command line,
and no Racket form is redefined or shadowed.  The macro is the whole interface.

@section[#:style 'unnumbered]{Pipeline}

@racket[#%python-code] runs seven passes, and only the last one writes Python:

@; the tables are hand-aligned text in a boxed block: the Markdown backend has no
@; table, and its flattened one runs cells together where a cell fills a column
@plain-code|{
pass                        in    out     what it does
core/expand-macro.rkt       LE    LE      a defmacro's macro is expanded where its name is bound
core/expand-cond.rkt        LE    LE      a cond becomes nested ifs, each clause body a begin
core/check-expression.rkt   LE    LE      refuses a statement where an expression belongs, and a Racket form that is not LE
core/check-scope.rkt        LE    LE      logs a warning for a name the program never binds
core/explicit.rkt           LE    LL      a form that takes a thunk gets an explicit lambda
core/lift.rkt               LL    LB      every procedure becomes a top-level define that takes what it captures
core/render.rkt             LB    Python  the source, with the pieces the program asked for
}|

The names a Python program has without the source defining them live in
@tt{core/names.rkt} as two parameters: @racket[runtime-names] (the pieces and
operators LE may use) and @racket[python-builtins] (the Python names a lifted
program may call).  Widen either before a module's @racket[#%python-code] forms
and the scope check stops warning about what you added:

@codeblock|{
(begin-for-syntax (runtime-names (cons 'sys (runtime-names))))
}|

@tt{core/names.rkt} is also the one module that says what a name is in Python,
and @tt{core/params.rkt} is the one the parameter list of @racket[define] and
@racket[lambda], the arguments a call hands a procedure and the keyword
arguments in both come from.

@section[#:style 'unnumbered]{LE}

Inside @racket[#%python-code] the language is LE, a small Lisp in Racket's
s-expression syntax.  A statement is what a body, a @racket[begin] in statement
position and the branch of a statement @racket[if] are made of; an expression is
what an @racket[if], a call argument and a @racket[begin] in expression position
are made of.  Nothing in an expression position is a statement, so a definition
cannot hide inside one and mean something else there, and
@racket[with-handler] and @racket[trampoline] are expressions like any other:
the handler runs where it stands, and a value position guards it.

@plain-code|{
s ::= e                                  an expression, for its value or its effect
    | (define x e)                       bind a value
    | (define (x p* ...) s* ...)         bind a procedure
    | (define (x p* ... . rest) s* ...)  bind a procedure; the rest parameter
    |                                    collects the arguments into a list
    | (set! x e)                         assign
    | (begin s ...)                      a sequence, of statements here
    | (if e1 s1 s2)                      a conditional of statements
    | (cond [e s* ...] ...)              the first clause whose test is true; else is last

e ::= x                                  variable, a Python global
    | l                                  self-evaluating literal
    | 'd                                 quoted datum
    | (import x)                          the module the name or string x names
    | (lambda (p* ...) s* ...)           a procedure, lifted like a define
    | (if e1 e2 e3)                      conditional
    | (cond [e e* ...] ...)              the first clause whose test is true; else is last
    | (begin e1 e* ...)                  a sequence, of expressions here
    | (raise e1)                         raise an exception
    | (with-handler e1 s* ...)           run the body with e1 handling what it raises
    | (trampoline s* ... e)              call what the last body returns while it is a procedure
    | (e0 a* ...)                        application, with keyword arguments

p ::= x | #:k x                          a parameter: positional, or the parameter
                                         of the keyword k
a ::= e | #:k e                          an argument: positional, or the keyword k

d ::= int | float | string | boolean | list | tuple | dict
l ::= int | float | string | boolean | tuple | dict
}|

A procedure body is a sequence of statements, and its value is the last
expression in it.  The body of a @racket[with-handler] or a @racket[trampoline]
is a statement sequence too: when it holds @racket[define] or @racket[set!] it
becomes a nested @racket[def] that runs where the form stands, and a lone
expression stays an inline @racket[lambda].  A @racket[trampoline] ends with the
expression whose value it calls.

@racket[set!] of a name the program defines at the top level becomes
@racket[global]; @racket[set!] of a name the program never defines is a plain
Python assignment, and the compiler says so.  A procedure that @racket[set!]s a
variable it captures is a compile error: a lifted procedure receives what it
captures as parameters, so there is nothing to assign to.  A capture that is
shadowed where the procedure is used is a compile error too -- rename one of the
two.

@racket[lambda] takes the same parameter lists as @racket[define] -- a rest
parameter included, and it collects into a list -- and its body is a statement
sequence like a procedure body, with the value of its last expression.

@racket[cond] runs the body of the first clause whose test is true, and a clause
body is an implicit @racket[begin], so it may hold several forms; @racket[else]
is the last clause, and a @racket[cond] with no @racket[else] raises when no
test is true.

@section[#:style 'unnumbered]{Data}

@racket[quote] is data: integers, floats, strings, booleans, lists, tuples and
dicts.  A list is a Python list, a tuple is @racket[#(1 2)] and becomes
@tt{(1, 2)}, and a dict is @racket[#hash(("a" . 1))] and becomes @tt{{"a": 1}},
so dict keys are strings.  There is no symbol type, so quoting a symbol is a
compile error, and there is no @racket[eval] and no @racket[gensym]: the one
way a program makes a name of its own is @racket[gensym] in a macro, and a macro
is the one place to ask for it.  A keyword
is not data either: @racket[#:k] is the syntax of a keyword argument, so
@racket[(quote #:k)] and @racket[#(1 #:k)] are compile errors too.

@section[#:style 'unnumbered]{Names}

@itemlist[
@item{A free identifier is a Python global: @racket[(print (len "abc"))]
becomes @tt{print(len("abc"))}.}
@item{@tt{core/names.rkt} owns what a name is in Python: @racket[python-name] is
the conversion, @racket[python-keyword-name] is a keyword argument's name,
@racket[piece-name] is what a piece is called, no pass spells a Python name out,
and the conversion reads the name and @racket[python-name-style] and nothing
else.  The Python name of a top-level define is therefore knowable from the
source alone, which is what a program that exports its names reads.  The rules
are below.}
@item{Operators are @bold{syntax}, not procedures.  With two or more operands
they are infix: @tt{+ - * / quotient modulo expt}, @tt{& | ^ << >>},
@tt{= not= < > <= >=} (@racket[equal?] is @tt{=}, @racket[eq?] is @tt{is}),
@racket[in], @racket[and], @racket[or].  With one operand @racket[not], @tt{-}
and @tt{~} are prefix, and @racket[(+ x)] is @racket[x].  An operator is never
a value: @racket[(apply + xs)] and @racket[(print +)] are refused, so define a
procedure when the procedure itself is wanted.}
@item{A name the program never binds is a Python global, which is the point, but
the compiler logs a warning about it: a reference to a name no @racket[define]
or parameter binds, and a @racket[set!] of one.  Python builtins (@racket[print],
@racket[len], ...) and the pieces below are known, so they stay quiet.  The
warnings are logged at warning level, so @tt{PLTSTDERR=warning} is how you see
them.}
@item{A procedure the program names comes with the piece it needs, and nothing
else does.  The pieces are exactly:}]

@plain-code|{
source                          Python
(raise e)                       raise_, Raised
(with-handler h e ...)          with_handler
(trampoline s* ... e)           trampoline
begin in an expression          begin
(import x)                      import_module
(list 1 2)                      list
(apply f xs)                    apply
(keyword-apply f kw xs)         keyword_apply
(object-ref xs 0)               object_ref
(object-set! xs 0 1)            object_set_b
(object-get-attr xs "append")   object_get_attr
(object-set-attr! xs "a" 1)     object_set_attr_b
(object-has-attr? xs "append")  object_has_attr_p
}|

Each of those names is what the piece is called under the prefix
@racket[prelude-prefix] -- an identifier's worth of a UUID, which the compiler
asks for once a run -- so no name a program writes is one of the prelude's.  Pin
it to nothing and the names read as the table does.  A piece that answers to an LE name -- the last eight -- is
named by the same conversion as any name, so the call and the @tt{def} agree in
either style: @racket[(object-ref xs 0)] is @tt{object_ref(xs, 0)} in one and
@tt{objectRef(xs, 0)} in the other.  A name a program gives its own definition
is the program's own where it is bound -- a program that defines @racket[list]
gets its own @racket[list], as it would in Python -- while the compiler's own
calls to a piece are the prefixed ones and out of the program's reach.

@subsection[#:style 'unnumbered]{The conversion}

A @tt{-} ends a word of a name, @tt{?} and @tt{!} are words of their own -- the
predicate and the bang -- and a name that is a Python keyword takes a trailing
@tt{_} while one that starts with a digit takes a leading one:

@plain-code|{
name                'snake, the default   'camel
even?               even_p                 evenP
set-car!            set_car_b              setCarB
object-ref          object_ref             objectRef
a--b                a__b                   a_B
a-                  a_                     a_
class               class_                 class_    a Python keyword
1st                 _1st                   _1st      a name cannot start with a digit
}|

With @racket['snake] the words are joined with @tt{_}; with @racket['camel] the
letter after a @tt{-} is capitalized instead, and a @tt{-} that has no letter
after it is joined, so no name is lost.

A name that already spells its Python name -- one with an @tt{_} in it --
is left as it is, so a Python keyword argument that is not one word can be
written exactly: @racket[#:format_spec] is @tt{format_spec} in either style.

@racket[python-name-style] is the
parameter that chooses, and it is set where the compiler runs, before the forms
it is meant for:

@codeblock|{
(begin-for-syntax (python-name-style 'camel))
}|

@racket[python-name] is provided at that phase too, so
@racket[(begin-for-syntax (python-name 'object-ref))] is the name a form would
use.  @racket[python-name] takes a prefix and a suffix as well, which are Python
text put around the conversion and not converted themselves.

A keyword argument's name is converted as a name is -- @racket[#:foo-bar] is
@tt{foo_bar} in one style and @tt{fooBar} in the other -- and the keyword a
Python function takes is converted the same way, whether or not the program
defines the procedure it calls.

A name the compiler makes up for itself is @tt{_lift_3f9a1b2c}, or
@tt{_lift_3f9a1b2c_inner} for a procedure the program called @tt{inner}, and the
prelude's names carry a prefix of the same kind: the compiler takes both from a
UUID, so no name it makes up is one a program wrote, and a name the program
defines at the top level is its own in the Python.  Two top-level names that are one Python name -- @tt{x-y} and
@tt{x_y} -- are a compile error, so a name of the program is one name in the
module.  What is compared is the Python name in both directions, so a program
that defines @racket[x-y] and writes @racket[x_y] anywhere -- a call, a
reference, a @racket[set!] -- is writing the name it defined, and a parameter
list that spells one Python name twice is refused as well.

@section[#:style 'unnumbered]{Keyword arguments}

A parameter list takes keyword parameters, written @racket[#:k k], and a call
hands a procedure keyword arguments the same way:

@plain-code|{
(define (area w #:height height)        def area(w, *, height):
    (* w height))                           return (w * height)
(area 3 #:height 4)                     area(3, height=4)
}|

The star is what makes @tt{height} keyword-only in Python, and it stands where
the rest parameter would: @tt{(define (f a #:k k . rest) ...)} is
@tt{def f(a, *rest, k)}.  A keyword parameter is keyword-only where the
procedure is called, as it is in Racket.

A keyword's name is a name, converted as a name is: @racket[#:foo-bar] is
@tt{foo_bar} and @racket[#:even?] is @tt{even_p}.  In Python a keyword and the
parameter it fills are one name, so the parameter has to be that name --
@racket[#:k k], and not @racket[#:k v], which is a compile error.  The same
conversion names the keyword a Python function takes, whether or not the
program defines the procedure:

@plain-code|{
(sorted xs #:reverse #t)                sorted(xs, reverse=True)
(round x #:ndigits 2)                   round(x, ndigits=2)
}|

A call writes its keyword arguments where it likes, Racket's way; the Python it
renders puts the positional arguments first and the keyword ones after, which is
also the order Python evaluates them in:

@plain-code|{
(f 1 #:k 2 3)                           f(1, 3, k=2)
}|

A keyword is syntax, not a value: it names an argument where a call writes one
and a parameter where a parameter list takes one, and it is never a datum, so
@racket[(quote #:k)] is refused.  One keyword takes one value, and two
arguments that are one Python name after the conversion -- @racket[#:x-y] and
@racket[#:x_y] -- are the one keyword, which is a compile error rather than the
@tt{SyntaxError} Python would raise.

@racket[apply] carries a keyword argument to the function it calls, which is the
function the keyword is for: @racket[(apply f xs #:k v)] is @tt{f(*xs, k=v)}.

A macro takes keyword arguments too -- @racket[(defmacro (m x #:k k) ...)] is
called @racket[(m 1 #:k 2)] -- and a transformer is a Racket procedure, so those
keywords are Racket's: they are not converted, one may carry a default,
@racket[#:k [k 5]], and two of them are two keywords over there whatever they
would be in Python.

@section[#:style 'unnumbered]{Truth and tail calls}

Only @racket[#f] is false.  An @racket[if] compiles to
@tt{(then if test is not False else else)}, so @tt{0}, @tt{""} and
@racket[(quote ())] are true, as they are in Racket; @racket[and], @racket[or]
and @racket[not] are Python's operators and keep Python's truth.

Tail calls are explicit.  @racket[trampoline] calls what its last body returns,
and keeps calling while that value is a procedure, so a procedure that returns a
thunk for its tail call loops flat and one that returns anything else is done.
Nothing is recognised for you: the compiler does not look for a tail call and
does not wrap one, so the thunk is yours to write.

@codeblock|{
(define python
  (#%python-code
    (define (count n acc)
      (if (= n 0) acc (lambda () (count (- n 1) (+ acc 1)))))
    (print (trampoline (count 100000 0)))))

(displayln python)     ; the Python source; running it prints 100000
}|

@section[#:style 'unnumbered]{Macros and reaching outside}

A macro is written outside the program, in Racket, with @racket[defmacro], and
used inside @racket[#%python-code]:

@codeblock|{
(defmacro (twice form) `(begin ,form ,form))

(define python
  (#%python-code
    (twice (print "hi"))))
}|

The body runs while the program is compiled, on the argument forms as data, and
what it returns takes their place; a macro may expand into anything LE has,
@racket[cond] included, and into another macro.  There is no hygiene: the
expansion is re-syntaxed where it is used, so a name the macro writes can
capture one the program already has -- ask @racket[gensym] for a name of its
own when that matters:

@codeblock|{
(defmacro (bind-tmp value body)
  (define name (gensym 'tmp))
  `(begin (define ,name ,value) ,body))
}|

A macro is a syntax binding: it is visible after the @racket[defmacro] in its
own module, or in a module that requires the one that wrote it, and nowhere
else, so a macro has to be defined before the @racket[#%python-code] form that
uses it.  A macro's name shadows an LE name of the same name inside the program.

Two macros may share a name if they live in different spaces.  The space is part
of the binding's name, so @racket[(defmacro #:space math (twice form) ...)]
binds @tt{math.twice}, and @racket[#:space] at the front of a form says which
space that form and its subforms are in:

@codeblock|{
(defmacro #:space math (twice form) `(print (* 2 ,form)))
(defmacro #:space text (twice form) `(print ,form ,form))

(define python
  (#%python-code
    (#:space math (twice 21))    ; the macro in space math
    (#:space text (twice "hi"))  ; the macro in space text
    (twice "plain")))            ; no space: the plain name, as ever
}|

@racket[#%python-code] takes the same keyword to put a whole body in a space,
@racket[(#%python-code #:space math form ...)], and because the keyword comes
first a macro call can hand a form in another space to another macro: an inner
@racket[#:space] overrides the one around it for its own form and subforms.
@racket[(#:space #f name arg ...)] is the plain name inside a spaced body.  The
key is a datum (a name is usual), it is not one of the macro's arguments, and a
spaced macro is provided and required under its dotted name, @tt{math.twice}.

A name is looked up in the space around it, so inside a spaced body a plain name
that no macro in that space matches is an ordinary Python call, as it always
was; a @racket[#:space] form that names no macro is a compile error.

A macro of your own is not the only way to grow sugar: a Racket macro can expand
to @racket[#%python-code], or build the LE forms as data and hand them to it:

@codeblock|{
(define-syntax-rule (python-twice e) (#%python-code (print e) (print e)))
(displayln (python-twice (quote (1 2))))
;; the source it renders is print([1, 2]) twice, so running it prints two lines
}|

There is no @racket[#%python-code] at run time: it is expanded away, and what a
program does with the string is up to it.

@tt{CHANGELOG.md} says what changed in each version.  Both @tt{README.md} and
@tt{CHANGELOG.md} are generated: edit @tt{scribblings/readme.scrbl} and
@tt{scribblings/changelog.scrbl}, then run @tt{./build-docs.sh}.

@section[#:style 'unnumbered]{Tests}

@codeblock|{
$ PLTCOLLECTS="$PWD/..:" TMPDIR="$PWD/.tmp" raco test tests/
}|

The tests use the macro directly, look at the Python it renders, and run it with
@tt{python3}; @tt{tests/names.rkt} pins the conversion itself, character by
character and in both styles.  @tt{PLTCOLLECTS} is only needed when an older
copy of the package is installed; with the package installed,
@tt{raco test -x -p rkt-pythonize} is enough.

@section[#:style 'unnumbered]{Layout}

@codeblock|{
main.rkt                     the library: #%python-code
core/check-expression.rkt    LE -> LE: statement/expression context
core/check-scope.rkt         LE -> LE: lexical scope and warnings
core/explicit.rkt            LE -> LL: make-explicit
core/lift.rkt                LL -> LB: procedures lifted to the top level
core/render.rkt              LB -> Python
core/names.rkt               what a name is in Python, and the name tables
core/params.rkt              parameter lists, and the arguments of a call
tests/dsl.rkt                end-to-end tests
tests/names.rkt              the conversion, character by character
tests/camel.rkt              a module that set the name style
scribblings/rkt-pythonize.scrbl  the manual
scribblings/readme.scrbl     the README, also the manual's first chapter
scribblings/changelog.scrbl  the changelog, also the manual's last chapter
build-docs.sh                renders both into README.md and CHANGELOG.md
CHANGELOG.md                 what changed in each version
}|

@section[#:style 'unnumbered]{Design notes}

@itemlist[
@item{Clojure is the inspiration for the shape of the compiler, not for the
syntax: one small compiler instead of a pipeline of passes, no CPS, and
generated Python that stays readable.}
@item{One macro, seven passes, and the pipeline they form is at the top of this
file.  Nothing is replaced and nothing is wrapped; the only thing the library
knows about Racket is how to be a macro.}
@item{There is no separate @tt{core.py} and no runtime library beyond the pieces
above.}
@item{@tt{raco setup rkt-pythonize} builds the manual.}]

@section[#:style 'unnumbered]{License}

Apache-2.0 OR MIT.
