#lang scribble/manual

@require[@for-label[(except-in rkt-pythonize #%top #%module-begin)
                    racket/base]]

@title{rkt-pythonize}
@author{zhanghao}

@defmodule[rkt-pythonize]

@bold{rkt-pythonize} is a Racket-hosted DSL that compiles to Python.  A module
written in @hash-lang[] @racketid[rkt-pythonize] @emph{is} a Python program: the language
expands the module body at compile time, compiles it to Python, and the module
exports the result as @racket[python-code].  The executable only writes that
string out.

@table-of-contents[]

@section[#:tag "quick"]{Quick start}

@codeblock|{
#lang rkt-pythonize
(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(print (fact 5))
}|

@codeblock|{
$ raco rkt-pythonize fact.rkt
$ python3 fact.py
120
}|

The Python is a value as well, so a Racket program can have it:

@verbatim|{
> (require (file "fact.rkt"))
> (display python-code)
# generated by rkt-pythonize
def fact(n):
    return (1 if (n == 0) is not False else (n * fact((n - 1))))

print(fact(5))
}|

@defthing[python-code string?]{The Python source of the module, as a string.  Every
@hash-lang[] @racketid[rkt-pythonize] module exports it.}

@section{The language}

@itemlist[
@item{@racket[racket/base] is re-exported as it is, so @racket[define],
@racket[lambda], @racket[if], @racket[begin], @racket[set!], @racket[quote] and
@racket[define-syntax] are Racket's.  A macro written with
@racket[define-syntax-rule] is an ordinary Racket macro, it runs at compile
time, and hygiene is Racket's.}
@item{What this language adds has an @racket[lb:] prefix:
@racket[lb:raise], @racket[lb:trampoline] and @racket[lb:with-handler].}
@item{Only @racket[#f] is false.  An @racket[if] compiles to
@racket[(then if test is not False else else)], so @racket[0], @racket[""] and
@racket[(quote ())] are true, as they are in Racket.}
@item{A free identifier is a Python global: @racket[(print (len "abc"))]
becomes @racket[print(len("abc"))].  Names are munged into readable Python
identifiers -- @racket[even?] is @racket[even_p], @racket[set-car!] is
@racket[set_car_b], @racket[object-ref] is @racket[object_ref] -- and a name
that is a Python keyword gets a trailing @racketid[_].}
@item{@racket[+], @racket[-], @racket[*], @racket[/], @racket[quotient],
@racket[modulo], @racket[expt], @racket[=], @racket[<], @racket[>],
@racket[<=], @racket[>=], @racket[equal?] and @racket[eq?] become Python's own
operators, and @racket[not] becomes Python's @racket[not].}
@item{@racket[quote] is data: integers, floats, strings, booleans, lists (which
are Python lists) and dicts whose keys are strings.  There is no symbol type, so
quoting a symbol is a compile error, and there is no @racket[eval] and no
@racket[gensym].}
@item{@racket[require] and @racket[provide] compile to nothing: they are about
the Racket module, not about the Python program.  A required library's
@emph{macros} work when their expansion is compilable; its procedures are Racket
procedures and are not available to the Python program.}]

@section{Statements and expressions}

An @racket[if] or a @racket[begin] in statement position becomes a Python
statement, so its branches can hold @racket[set!] and other statements; the same
forms in an expression position become a Python conditional expression and a
call to @racket[_begin].  That is what makes Racket's own control forms work:

@codeblock|{
#lang rkt-pythonize
(define x 0)
(when #t (set! x 5))
(unless #f (set! x (+ x 1)))
(if (> x 5) (set! x (* x 2)) (set! x 0))
(print (cond [(= x 12) "twelve"] [else "other"]))
(print (and #t x))
}|

Not compilable: @racket[let], @racket[let*], @racket[or] and @racket[case] (they
expand to @racket[lambda]s or to @racket[let-values] with bindings), a
@racket[lambda] that is not a definition's value, @racket[set!] of an unbound
name, and Racket library procedures such as @racket[third] (they would be Python
globals and fail as @racket[NameError]s unless the Python program defines them).

@section{The @racket[lb:] forms}

@defform[(lb:raise e)]{Raise @racket[e].  The value travels as a Python
exception.}

@defform[(lb:with-handler h e)]{Run @racket[e] with @racket[h] as the handler of
what it raises.  The body runs where it stands, so a value position guards it:

@codeblock|{
(define (recover e) (+ e 1))
(print (lb:with-handler recover (lb:raise 41)))          ; 42
(print (if #f (lb:with-handler recover (lb:raise 1)) 7)) ; 7
}|}

@defform[(lb:trampoline e)]{Call what @racket[e] returns while it is a
procedure, so a body that ends in a tail call loops flat and a body that returns
anything else is done:

@codeblock|{
(define (count n acc)
  (lb:trampoline (if (= n 0) acc (count (- n 1) (+ acc 1)))))
(print (count 100000 0))                                 ; 100000
}|

A procedure that drives @racket[lb:trampoline] is emitted twice: @racket[f]
drives and @racket[f_body] holds the bounces, so a bounce never re-enters a
driver.}

@section{Runtime pieces}

The generated program carries only the pieces it uses, each named after the form
or the procedure that asked for it.

@(tabular
  (list (list @bold{source} @bold{Python})
        (list @racket[(lb:raise e)] @elem{@racket[_raise] and @racket[_Raised]})
        (list @racket[(lb:trampoline e)] @racket[_trampoline])
        (list @racket[(lb:with-handler h e)] @racket[_with_handler])
        (list @racket[begin] @elem{in an expression: @racket[_begin]})
        (list @racket[(list 1 2)] @racket[list])
        (list @racket[(apply f xs)] @racket[apply])
        (list @racket[(keyword-apply f kw xs)] @racket[keyword_apply])
        (list @racket[(object-ref xs 0)] @racket[object_ref])
        (list @racket[(object-set! xs 0 1)] @racket[object_set_b])
        (list @racket[(object-get-attr xs "append")] @racket[object_get_attr])
        (list @racket[(object-set-attr! xs "a" 1)] @racket[object_set_attr_b])
        (list @racket[(object-has-attr? xs "append")] @racket[object_has_attr_p])
        (list @racket[(void)] @racket[None])))

@section{Command line}

@codeblock|{
$ raco rkt-pythonize [-o <output>] <module.rkt>
}|

@racket[<module.rkt>] becomes @filepath{<module>.py}.  With @racket[-o -] the
Python goes to standard output, and with @racket[-o <output>] to that file.
Before the package is installed, the same entry point runs as
@codeblock|{
$ racket cli.rkt [-o <output>] <module.rkt>
}|

@section{Tests}

@codeblock|{
$ TMPDIR="$PWD/.tmp" raco test tests/
}|

The end-to-end tests compile a @hash-lang[] @racketid[rkt-pythonize] module in a
subprocess and run the generated program with @exec{python3}.  The subprocess
gets a @envvar{PLTCOLLECTS} that points at the checkout, so the checkout wins
over an installed copy of the package.
