#lang racket/base
(require nanopass/base racket/list "handler.rkt")
(provide L14 parse-L14 unparse-L14 expand-defines)

(define-language L14
  (extends L13)
  (Expr (e body)
    (+ (define x e)
       (define (x x* ...) body ...))))

(define-parser parse-L14 L14)

(define (define-form? expr)
  (nanopass-case (L14 Expr) expr
    ((define ,x ,e) #t)
    ((define (,x ,x* ...) ,body ...) #t)
    (else #f)))

(define (flatten-begins body)
  (foldr (lambda (e acc)
           (nanopass-case (L14 Expr) e
             ((begin ,e* ...) (append (flatten-begins e*) acc))
             (else (cons e acc))))
         '()
         body))

(define none-expr (parse-L14 'none))

(with-output-language (L13 Expr)
  (define (process-body body expand)
    (define flattened (flatten-begins body))
    (define-values (defs rest) (partition define-form? flattened))
    (if (null? defs)
        (let ((rest* (map expand rest)))
          (cond ((null? rest*) (expand none-expr))
                ((null? (cdr rest*)) (car rest*))
                (else `(begin ,rest* ...))))
        (let* ((norms (map (lambda (d)
                             (nanopass-case (L14 Expr) d
                               ((define (,x ,x* ...) ,body ...)
                                (list x `(lambda (,x* ...) ,(process-body body expand))))
                               ((define ,x ,e)
                                (list x (expand e)))))
                           defs))
               (binds-x* (map car norms))
               (binds-e* (map cadr norms))
               (rest* (map expand rest))
               (rest-body (cond ((null? rest*) (expand none-expr))
                                ((null? (cdr rest*)) (car rest*))
                                (else `(begin ,rest* ...)))))
          `(letrec ([,binds-x* ,binds-e*] ...) ,rest-body)))))

(define-pass expand-defines : L14 (ir) -> L13 ()
  (Expr : Expr (ir) -> Expr ()
    ((define ,x ,e)
     (error 'expand-defines "internal define not hoisted: ~a" x))
    ((define (,x ,x* ...) ,body ...)
     (error 'expand-defines "internal define not hoisted: ~a" x))
    ((lambda (,x* ...) ,body ...)
     `(lambda (,x* ...) ,(process-body body expand-defines)))
    ((let/cc ,x ,body ...)
     `(let/cc ,x ,(process-body body expand-defines)))
    ((with-handler ,[e] ,body ...)
     `(with-handler ,e ,(process-body body expand-defines)))
    ((begin ,e* ...)
     (process-body e* expand-defines))
    ((let ((,x* ,[e*]) ...) ,body ...)
     `(let ((,x* ,e*) ...) ,(process-body body expand-defines)))
    ((letrec ((,x* ,[e*]) ...) ,body ...)
     `(letrec ((,x* ,e*) ...) ,(process-body body expand-defines)))
    ((let* ((,x* ,[e*]) ...) ,body ...)
     `(let* ((,x* ,e*) ...) ,(process-body body expand-defines)))
    ((let ,x ((,x* ,[e*]) ...) ,body ...)
     `(let ,x ((,x* ,e*) ...) ,(process-body body expand-defines)))
    ((cond (,e0 ,e1 ...) ... (else ,e* ...))
     (define pairs (map cons e0 e1))
     (define processed-clauses
       (map (lambda (p)
              `(,(expand-defines (car p)) ,(process-body (cdr p) expand-defines)))
            pairs))
     (define else-body (process-body e* expand-defines))
     `(cond ,processed-clauses ... (else ,else-body)))
    ((set! ,x ,[e])
     `(set! ,x ,e))
    ((,[e0] ,[e*] ...)
     `(,e0 ,e* ...))))
